### ISSUE TITLE
Manual select() context

### ISSUE THREAD

**Issue by NiklasRosenstein** [ponyorm/pony#105]
I think it would be great if one could manually specify the context on which the `select()` methods resolves variables. That would allow me to do `select()` from a Jinja template. I couldn't find a solution with the current API (Pony 0.6) . I even tried using `select(eval('(%s)' % string, vars(myapp.db), context))` with no luck.

```python
@jinja2.contextfunction
def select(context, string):
    from myapp.db import User, Account, TaxGroup, Entry
    from flask import g
    return select(string)
```

**Comment by kozlovsky** [comment]
Hi, I added this functionality as part of PonyORM 0.6.1 release. Now it is possible to pass globals and locals as a second and third positional parameters to any PonyORM function or method which receives generator or lambda function. Examples:

```python
context = {'x': 3.5}
select((s for s in Student if s.gpa > x), context)
Student.select(lambda s: s.gpa > x, context)
```

Hope this allows to make queries from Jinja templates.

**Comment by NiklasRosenstein** [comment]
This is great, thank you!
