### ISSUE TITLE
CloudSQL Support

### ISSUE THREAD

**Issue by JakeAustwick** [ponyorm/pony#112]
I saw your comment here: http://stackoverflow.com/a/26945397/2175384

I am wanting to start a new project and am required to use CloudSQL. Am I going to hit problems if I just use the MySQL adapter?

**Comment by kozlovsky** [comment]
I haven't used CloudSQL by myself. From the programming point of view as far as I know CloudSQL looks just like a typical MySQL server. You just don't host it on your server. I think that MySQL adapter should support CloudSQL without any problem.
