### ISSUE TITLE
Add support for calculated fields

### ISSUE THREAD

**Issue by tonycpsu** [ponyorm/pony#115]
As per [this SO question](http://stackoverflow.com/questions/28586934/are-calculated-derived-fields-fully-supported-in-pony-orm), I'd like to add calculated/derived fields to my entities and then use those fields in calculations, aggregations, etc.  I wasn't able to find anything in the docs or examples that indicate that this is supported.  Could this kind of thing be supported in the future?

**Comment by kozlovsky** [comment]
Thanks for the suggestion!

This feature can be implemented relatively easily, because Pony already have the ability to [translate lambdas to SQL](http://doc.ponyorm.com/queries.html#Query.filter). I hope we can add calculated fields soon.

**Comment by tonycpsu** [comment]
That's great to know, thanks for the quick response.

**Comment by tonycpsu** [comment]
Any idea of when this might be available, or of a possible workaround?  I've got to make a decision in the next couple of weeks whether to continue with Peewee ORM or try to migrate to Pony ORM, and calculated fields are a must.  Thanks!

**Comment by kozlovsky** [comment]
I'll try to add this feature the next week and include it in the release 0.6.2

**Comment by tonycpsu** [comment]
Excellent!

**Comment by Vitalium** [comment]
Seems, this feature is not included in 0.6.5, or am I doing something wrong?

**Comment by sio2sio2** [comment]
something new? Is it harder than you thought at first?

**Comment by tonycpsu** [comment]
@kozlovsky: is this still on your radar?

**Comment by bagibence** [comment]
Hybrid methods and properties were introduced in 0.7.4: https://docs.ponyorm.com/entities.html#hybrid-methods-and-properties

**Comment by kozlovsky** [comment]
Thanks, I forgot to close this issue

**Comment by tonycpsu** [comment]
@kozlovsky : this is a great addition, but I find that it's a bit limited in that the return statement has to be rather simple and can't use any other methods or modules or I get things like ` Function 'name_to_short' cannot be used this way: name_to_short(self.name_full) (inside Player.name_short)`.  Are there any plans to allow more arbitrary expressions?

**Comment by sashaaero** [comment]
@tonycpsu what do you exactly mean? Can you give an example?
Just let you know - Pony translates hybrid methods to SQL, so we have limitations. You can't translate any algorithm on Python to SQL.

**Comment by tonycpsu** [comment]
@sashaaero : An example I just ran into.  With this schema:

```
class Item(db.Entity):

    item_id = PrimaryKey(int, auto=True)
    created = Required(datetime, default=datetime.now())
    @property

    def age(self):
        return datetime.now() - self.created
```
the following query:
```
Item.select().order_by(
    lambda i: i.age
)
```

results in `TypeError: Unsupported operand types 'datetime' and 'datetime' for operation '-' in expression: datetime.now() - self.created (inside Item.age)`

**Comment by sashaaero** [comment]
First of all you have incorrect usage of `default`. You should pass function `default=datetime.now` as argument. I'll take a closer look on this soon.

**Comment by sashaaero** [comment]
@tonycpsu I got it. It's not a problem with hybrids itself, it is the problem with our realization of minus for datetimes. We'll fix it soon.

**Comment by Elijas** [comment]
> @tonycpsu I got it. It's not a problem with hybrids itself, it is the problem with our realization of minus for datetimes. We'll fix it soon.

Is this still not solved? https://github.com/ponyorm/pony/issues/438
