### ISSUE TITLE
Any way to pass variable attribute names to Entity.select / get?

### ISSUE THREAD

**Issue by tonycpsu** [ponyorm/pony#124]
I'd like to add a class method to one of my entity classes that allows me to find an entity by any number of key fields.  I was looking at something like:

    @classmethod
    def get_by_ids(cls, ids):

        for field, i in ids.items():

            p = cls.get(field = i)
            if p:
                return p
        return None

Where "ids" is an ordered dictionary of id field and value pairs, e.g. ```{ 'foo_id': 123, 'bar_id': 456}```.  Of course the problem is that the ```.get()``` method wants to look for a an attribute named ```field``` instead of whatever the actual value of the ```field``` variable is.  Is there any way to accomplish something like this, or do I have to hard-code the key field names into this function and test them individually?

**Comment by tonycpsu** [comment]
Eh, ```eval()``` works and for what I'm doing is probably okay.

**Comment by kozlovsky** [comment]
If you speak about composite primary key, you can pass tuple of attributes to `__getitem__` class method:

pk = (1, 2, 3)
obj = cls[pk]

If you want to lookup an object using some arbitrary composite key, you can pass a dictionary of attribute values to the `get` method of the entity class:

vals = {'a': 1, 'b': 2, 'c': 3}
obj = cls.get(**vals)

P.S. Sorry for delay in responding to your other issues, they are all valid and I plan to return to them really soon. I just a bit overloaded right now with our new release - we are implementing some unique feature that have no analogs in other ORMs.
