### ISSUE TITLE
LIKE ESCAPE selection

### ISSUE THREAD

**Issue by stsouko** [ponyorm/pony#128]
in postgres doc I found this:
'abc' LIKE 'abc'    true
'abc' LIKE 'a%'     true
'abc' LIKE '\_b\_'    true
'abc' LIKE 'c'      false

how to implement in pony operation "'abc' LIKE '\_b\_'    true" if "\_" escaped every time.
select(x for x in A if '\\\_b\\\_' in x.s) don't work

**Comment by kozlovsky** [comment]
In Python there is no direct equivalent to `'abc' LIKE '_b_'`

You can do it using raw SQL fragment:

```python
select(x for x in A if raw_sql("x.s LIKE '_b_'"))
```
`raw_sql()` function was recently added to development version of PonyORM and will be part of the next release 0.6.2. Inside the raw SQL expression `x` is the table alias name and `s` is the column name.

Another option is to rewrite query in the following way:

```python
select(x for x in A if len(x.s) == 3 and x[1] == 'b')
```

**Comment by stsouko** [comment]
Thank you so much!

raw_sql() is very useful
