### ISSUE TITLE
adding new methods to entities

### ISSUE THREAD

**Issue by d555** [ponyorm/pony#143]
Is there any way to add a method to entity after his definition in an appropriate way? Because I had tried it, but pony rise ImplementionError. I've found out, that I can add a method iff the method starts and ends with underscore like the following: `Entity._newmethod_` and everything works like charm. But,  I really want to call the method without the underscores. Or I am doing something wrong? Thanks. 

Btw. I added the methods with a decorator, wrapped them with that.

Thanks authors.

**Comment by kozlovsky** [comment]
This restriction is obsolete, I'll remove it. Now it will be possible to freely assign methods to entities. This will be part of the next release PonyORM 0.6.2
