### ISSUE TITLE
count() giving small results

### ISSUE THREAD

**Issue by mattseh** [ponyorm/pony#146]
Hi,

In [3]: models.Keyword.select(lambda k: models.count(k.users)).count()
Out[3]: 2L

In [6]: len(models.Keyword.select(lambda k: models.count(k.users))[:])
Out[6]: 12420

This is a many-to-many relationship, is this something about Pony I don't understand, or a bug?

Thanks

**Comment by kozlovsky** [comment]
Hi Mattseh!

It looks like a bug. Can you provide the SQL text for these queries? You can see it in logs after performing `sql_debug(True)`, or you can read `db.last_sql` attribute right after the query execution.

**Comment by mattseh** [comment]
In [2]: models.sql_debug(True)

In [3]: models.Keyword.select(lambda k: models.count(k.users)).count()
GET CONNECTION FROM THE LOCAL POOL
SWITCH TO AUTOCOMMIT MODE
SELECT COUNT(*)
FROM "Keyword" "k"
  LEFT JOIN "Keyword_User" "t-1"
    ON "k"."id" = "t-1"."keyword"
GROUP BY "k"."id"
HAVING COUNT(DISTINCT "t-1"."user") <> 0

Out[3]: 1

In [4]: len(models.Keyword.select(lambda k: models.count(k.users))[:])
SELECT "k"."id"
FROM "Keyword" "k"
  LEFT JOIN "Keyword_User" "t-1"
    ON "k"."id" = "t-1"."keyword"
GROUP BY "k"."id"
HAVING COUNT(DISTINCT "t-1"."user") <> 0

SELECT "id", "keyword", "country_code", "created", "scheduled", "updated"
FROM "Keyword"
WHERE "id" IN (?, ?)
[1, 2]

Out[4]: 2

Hope that helps :)

**Comment by kozlovsky** [comment]
Yes, this is a bug. In the first query Pony attempts to do optimization by replacing subquery to LEFT JOIN, but this optimization does not work when the query have two levels of aggregation. I'll fix it.

**Comment by kozlovsky** [comment]
Thanks for the reporting! This bug was already fixed by commit f5e409b8. It will be part of Pony ORM 0.6.2
