### ISSUE TITLE
Если вызвать `.flush()` то теряется транзакционная целостность.

### ISSUE THREAD

**Issue by vladlutkov** [ponyorm/pony#158]
``` python
from pony.orm import Database, db_session

db = Database()


class TestTable(db.Entity):
    pass


def init_database():
    db.bind("sqlite", ":memory:")
    db.generate_mapping(create_tables=True)


def clear_database():
    db.drop_all_tables(with_all_data=True)
    db.create_tables()

if __name__ == "__main__":
    init_database()

    try:
        with db_session:
            entity = TestTable()
            entity.flush()
            raise ValueError()
    except ValueError as exc:
        print(exc.args)
    with db_session:
        # в транзакции ошибка, а в таблице запись уже есть!
        if len(TestTable.select()) != 0:
            print("Таблица не пуста")

    clear_database()

    try:
        with db_session:
            entity = TestTable()
            raise ValueError()
    except ValueError as exc:
        print(exc.args)
    with db_session:
        # в транзакции ошибка, а в таблице записи нет, все ок
        if len(TestTable.select()) == 0:
            print("Все в порядке!")
```

Что как бы очень критичный баг.

Ну и менее важная проблема - как мне получить `id` только что созданного элемента?

**Comment by vladlutkov** [comment]
Еще вброс
``` python
from pony.orm import Database, db_session, Required

db = Database()


class TestTable(db.Entity):
    name = Required(str)

    def before_insert(self):
        print("before_insert name: {}".format(self.name))
        raise ValueError("before_insert")

    def before_update(self):
        print("before_update name: {}".format(self.name))
        raise ValueError("before_update")


def init_database():
    db.bind("sqlite", ":memory:")
    db.generate_mapping(create_tables=True)


def clear_database():
    db.drop_all_tables(with_all_data=True)
    db.create_tables()

if __name__ == "__main__":
    init_database()
    with db_session:
        entity = TestTable(name="WQE")
        entity.flush()
 
    with db_session:
        print("rows count: {}".format(len(TestTable.select())))
```
Если вызвать `.flush()` хук `before_insert` вообще не срабатывает!

**Comment by socketpair** [comment]
Slightly small example that triggers both bugs:

```python
from pony.orm import Database, db_session
db = Database()
class TestTable1(db.Entity):
    def before_insert(self):
        print('BI1')
class TestTable2(db.Entity):
    def before_insert(self):
        print('BI1')
db.bind("sqlite", ":memory:")
db.generate_mapping(create_tables=True)
try:
    with db_session:
        entity = TestTable1()
        entity.flush()
        print 'inserted ID is', entity.id
        raise Exception('test')
except Exception as e:
    if e.args[0] != 'test':
        raise
# HAY! print('BI1') was not executed!
with db_session:
    print len(TestTable1.select()) # print 1 instead of 0 !!!
print '-------------------'
try:
    with db_session:
        entity = TestTable2()
        list(TestTable2.select()) # force flush with another way
        print 'inserted ID is', entity.id
        raise Exception('test')
except Exception as e:
    if e.args[0] != 'test':
        raise
with db_session:
    print len(TestTable2.select()) # print 0 as expected
```

**Comment by vladlutkov** [comment]
Просто `pony.orm.flush()` работает как надо, т. е. записи в таблице не остается

**Comment by socketpair** [comment]
@vladlutkov а с `pony.orm.flush()` хук-то вызывается ?

**Comment by vladlutkov** [comment]
Еще проблема
``` python
from pony.orm import Database, db_session, flush, CommitException

db = Database()


class TestTable(db.Entity):
    def after_insert(self):
        raise ValueError("before_insert")

    def after_update(self):
        raise ValueError("before_update")


def init_database():
    db.bind("sqlite", ":memory:")
    db.generate_mapping(create_tables=True)


def clear_database():
    db.drop_all_tables(with_all_data=True)
    db.create_tables()

if __name__ == "__main__":
    init_database()
    try:
        with db_session:
            entity = TestTable()
            flush()
    except ValueError:
        print("ValueErrorRaised")

    clear_database()

    try:
        with db_session:
            entity = TestTable()
    except CommitException:
        print("CommitException raised")
```

Почему, казалось бы, в одинаковых ситуациях бросаются разные исключения?

**Comment by vladlutkov** [comment]
@socketpair да, хуки `before_*` работают, если вызвать `pony.orm.flush()`

**Comment by kozlovsky** [comment]
Hi everybody! Thank for the reporting!
We fixed this bug three days ago in commit ecab21bce4b527d0. If you check the latest version from GitHub all the examples should work correctly. The fix will be part of the release 0.6.3.

-----

Добрый день, мы как раз пофиксили этот баг буквально на днях! Теперь, когда вызывается `obj.flush()`, этот метод должен корректно работать с транзакциями, и вызывать `before_insert`.

Что касается `id` созданного объекта, то его значение должно быть доступно в объекте после `flush`.

Теперь по поводу исключений, хотя это не имеет прямого отношения к `flush` и лучше бы вынести в отдельный issue.

Когда мы выходим из `db_session`, пони пытается сделать flush и затем выполнить commit. В процессе этих действий теоретически может возникнуть множество разных ошибок. Но все они логически означают, что выполнить commit не удалось, хотя конкретные причины могут быть разные. Для того чтобы можно было обрабатывать ошибки, возникшие при выполнении commit, неким однородным образом, пони создает исключение `CommitException`, которое обертывает исходную ошибку (или несколько ошибок, если шла работа одновременно с несколькими объектами `Database`). Список исходных ошибок можно посмотреть в атрибуте `exceptions`.

Когда ошибка во время выполнения `flush` в методе `before_insert` возникает до выхода из `db_session`, она сейчас ни во что не оборачивается, потому что мы еще не пытаемся делать неявный commit.

Я думаю что определенная логика в текущем поведении есть, и не уверен что было бы правильно ее менять. Возможно, в дальнейшем кто-то сможет меня переубедить.

**Comment by socketpair** [comment]
ecab21bce4b527d0d27177c8c2776b2730a6422a достаточно для решения всех вышеназванных проблем? хочу накатить его на 0.6.2. ОООчень боюсь обновлять пони. или таки лучше обновить?

**Comment by socketpair** [comment]
Кстати, насчёт исключений. На мой взгляд, причина несрабатывания коммита может быть только одна (первая встретившаяся) (я не говорю о цепочке исключений типа `raise from`).

На мой взгляд, в `CommitException` должны преобразовываться только исключения пришедшие из драйвера БД. А исключения из хуков должны пробрасываться напрямую.

А так -- как раз таки наоборот, однородно не получается обрабатывать, и нужно обрабатывать оба вида исключений - и нативное (из хука) и `CommitException`. Потому что  `flush()` может вызваться опосредовано, а может и не вызваться, сразу перейдя к коммиту.

**Comment by kozlovsky** [comment]
If you use the `obj.flush()` method and not just global `flush()` function it is better to upgrade Pony to the latest GitHub version, because the behavior of `obj.flush()` was pretty wrong in 0.6.2. We plan to release 0.6.3 on the next Monday just for that bug. The should be no backward-incompatible changes between 0.6.2 and 0.6.3 except bugfixes.

**Comment by socketpair** [comment]
> behavior of obj.flush() was pretty wrong in 0.6.2

А мы это используем чуть более чем везде :(. ОК. будем ждать 0.6.3

**Comment by kozlovsky** [comment]
> Кстати, насчёт исключений. На мой взгляд, причина несрабатывания коммита может быть только одна (первая встретившаяся) (я не говорю о цепочке исключений типа `raise from`).

If you use single `Database` object, yes. But if you work with several databases in a single `db_session`, then it is possible that different databases raises different exceptions. But this is rather exotic situation.

> А так -- как раз таки наоборот, однородно не получается обрабатывать, и нужно обрабатывать оба вида исключений - и нативное (из хука) и `CommitException`. Потому что `flush()` может вызваться опосредовано, а может и не вызваться, сразу перейдя к коммиту.

There is a logic in you words, we should think about it a bit more tomorrow.

**Comment by socketpair** [comment]
@kozlovsky если перед реальным коммитом (внутри реализации `.commit()`) вызывать `flush()` для всех БД до `try..except`, которое нужно для обёртывания  в `CommitException`, то всё будет полностью логично. Тогда действительно, будут обёрнуты только исключения из движка БД.

**Comment by kozlovsky** [comment]
Sounds valid. I'll think about it a bit more, and probably will change exception handling in a way that you described. Since it is a backward-incompatible change, probably it is better to do the change after the 0.6.3 release, so anybody who uses `obj.flush()` can upgrade to 0.6.3 without any hassles.

**Comment by socketpair** [comment]
#159 created
