### ISSUE TITLE
SQL Views

### ISSUE THREAD

**Issue by danceasarxx** [ponyorm/pony#160]
I have a db of patients and would like to use an sql view for patient search, is it possible to extend Pony
to do this in my code and how(that's if pony can't do this already).

**Comment by kozlovsky** [comment]
Actually, we've discussed this topic internally just a few days ago, because it may be useful for our Pony-based project [fineartbiblio.com](https://fineartbiblio.com). So it is possible that we'll add support of SQL views relatively soon. But when speaking of SQL views support, different people can mean slightly different things. Can you describe your use case in more details? Can you suggest a possible API which suits your case?

**Comment by danceasarxx** [comment]
For now all I want to use the view for is search i.e. *a view with a smaller set of columns than the original database*. Hence kinda `read-only`.
For instance(*I know it looks basic*):

```python
class Patient(db.Entity):
    firstname = Required(str)
    surname = Required(str)
    age = Optional(int)

db.generate_mapping(create_tables=True)
PatientSearch = select((p.firstname, p.surname) for p in Patient)

# web view
patients = PatientSearch.filter(lambda p: req['firstname'] in p.firstname)
resp = json.dumps([p.to_dict() for p in patients])
```

How you will extract the column names I don't really know

**Comment by kozlovsky** [comment]
So, if I understand correctly, in your case it is not necessary to have SQL views _per se_, and what you want is to limit the number of attributes serialized to JSON. Right now you can specify it right in `to_dict` method:

```python
query = select(p for p in Patients)

resp = json.dumps([p.to_dict(only=['id', 'firstname', 'surname'])  for p in query])
# or
resp = json.dumps([p.to_dict(exclude=['age'])  for p in query])
```

The drawback of such approach is that the developer may forget to specify attributes in `to_dict` and accidentally serialize some sensitive information to JSON. We are working on an advanced system of permissions which should allow to specify in declarative form which user can see which attributes. This permission system will be able to restrict serialized data automatically.

**Comment by danceasarxx** [comment]
actually I am trying not to read some attributes from the database in the first place(*some binary data for instance*), hence the views. Maybe lazily loading the other attributes would do the trick.

```python
class Patient(db.Entity):
    firstname = Required(str, always=True)
    surname = Required(str, always=True)
    age = Optional(int)

db.generate_mapping(create_tables=True)
patientd = lazy_select(p for p in Patient)

resp = json.dumps([p.lazy_to_dict() for p in patients])
```

**Comment by kozlovsky** [comment]
We have [`lazy`](https://docs.ponyorm.com/entities.html#lazy) option. This option is `True` by default for `LongStr` attributes.

```python
class Person(db.Entity):
    name = Required(str)
    short_biography = Optional(str, lazy=True)
    detailed_biography = Optional(LongStr)  # LONGTEXT in MySQL, CLOB in Oracle
    binary_data = Optional(buffer, lazy=True)  # BLOB column
```

Lazy columns are not loaded until directly requested:

```python
p1 = Person[1]  # only id & name columns are loaded
print(p1.name)
print(p1.detailed_biography) # lazy loading of detailed_biography column
```

The `to_dict` method don't include lazy attributes by default:

```python
p1.to_dict()  # only id & name will be included
```

You can add lazy attributes explicitly:

```python
p1.to_dict(with_lazy=True, exclude=['detailed_biography', 'binary_data'])
```

Also you can specify explicitly which attributes you need:

```python
p1.to_dict(only=['id', 'name', 'short_biography'])
```

**Comment by danceasarxx** [comment]
I can't believe it :$. I am really sorry(I remember seeing this and ignoring it). But the views issue is still possible if not pressing, Thanks a lot.

**Comment by kozlovsky** [comment]
No problem :) Regarding views, I hope we can implement them in the future

**Comment by stsewd** [comment]
@AthusVieira the last time I used pony with views, I had to do it using `db.select()` with a raw query.

**Comment by AthusVieira** [comment]
@stsewd I used to use `db.select()` to work with views, but, you know, I think this could be better if we could write queries with less sql like we can do with Hibernate in Java. 

I mean, Views in Pony could be handled as tables. Something like this:

```
class UserView(db.View):
    _view_ = 'user_view'
    # the other fields
```

**Comment by kozlovsky** [comment]
@AthusVieira, can you describe your use case in more details? Do you already have some SQL view in database?

**Comment by AthusVieira** [comment]
Hey, @kozlovsky ! Of course. Let me explain.


Imagine this SQL View in my database:

```
CREATE VIEW `myview` AS
    SELECT 
        prj.projectid AS 'project_id',
        tt.testtype AS 'test_type',
        ps.projectstatus AS 'project_status'
    FROM
        tb_project prj
            INNER JOIN
        tb_test_type tt ON prj.testtypeID = tt.testtypeID
            INNER JOIN
        tb_project_status ps ON prj.projectstatusID = ps.projectstatusID
    WHERE
        1 = 1
    ORDER BY prj.projectid
```

With this View already created in my database, I'd be able to write a model that represents that SQL View. Something like this:

```
class MyView (db.View):
    _view_ = 'view'
    project_id = Field (Int)
    test_type = Field (str)
    project_status = Field (str)
```

After that I could write some query using the Pony's power. Something like this:

`my_views = select (v for v in MyView if v.project_id > 500)`

Of course that by working with Views I'd be able to only read/fetch the values. Update, Delete and Insertions would not be available in this way.


Let me know if I was clear with this. I'll be available to help if you need any assistance.

**Comment by kozlovsky** [comment]
I you can create SQL view manually you already able to use it. When defining models, just define entity as usual, and specify view name as a `_table_`. You will be able to select objects, but you should not try to update or delete them:

```python
class MyView(db.Entity):
    _table_ = 'myview'
    project_id = orm.Required(int)
    test_type = orm.Required(str)
    project_status = orm.Required(str)
```

**Comment by AthusVieira** [comment]
@kozlovsky, @stsewd  and @jgirardet I just tested it out and everything is working as expected. That's amazing!

However I think it's important to say that when working with PonyORM and Views you need to provide a column called `id` and only then you'll be able to map and work with the correspondent view.

The column `id` in your View can be a composition of the other fields.

Here what I did:

I created this view for test purpose using MySQL:

```
CREATE VIEW `my_view` AS
SELECT 
    (u.user_id + p.profile_id + current_timestamp) AS id,
    u.user_id AS user_id,
    p.profile_id AS profile_id
FROM
    user u
        JOIN
    profile p ON u.profile_id = p.profile_id
WHERE
    1 = 1
```

Then I wrote the model for this View. I looks like this:

```
class User(db.Entity):
    _table_ = 'user'
    user_id = PrimaryKey(int, size = 64, column = 'user_id', auto = True)
    username = Required(str)
    profile_id = Required('Profile')

class Profile(db.Entity):
    _table_ = 'profile'
    profile_id = PrimaryKey(int, size = 64, column = 'profile_id', auto = True)
    profile = Required(str)
    users = Set(User)

class MyView(db.Entity):
    _table_ = 'my_view'
    user_id = Required(int)
    profile_id = Required(int)

db.generate_mapping(create_tables = True)
```

Note that you don't need to specify the `id` column in your View (unless you need it). Just create it in the SQL View and you're ready to go!

That's all! Thanks everyone.

**Comment by AthusVieira** [comment]
Oh! I should not forget to mention the best part: You can use the Pony's power to handle you view, after all that's the reason of this conversation.

`views = select(v for v in MyView)[:]`
`views = MyView.select()`

And much more...
