### ISSUE TITLE
0.6.3 + entity.flush(): after_insert() does not work

### ISSUE THREAD

**Issue by socketpair** [ponyorm/pony#161]
This code does not call `after_insert()` hook. Also cannot check if that `ValueError` will be seen in `except ValueError as e`

```python

from pony.orm import Database, db_session

db = Database()

class TestTable(db.Entity):
    def after_insert(self):
        raise ValueError("a_i")

db.bind("sqlite", ":memory:")
db.generate_mapping(create_tables=True)
try:
    with db_session:
        entity = TestTable()
        entity.flush()
except ValueError as e:
    print("ValueError raised", e)
```

**Comment by socketpair** [comment]
Мы начинаем нервно посматривать на другие ORM. Ребят, ей богу, ну вот только что же говорили перед выпуском 0.6.3 о проблема с `flush`. можно же тесты сделать, наверно? Я переживаю, что код стал слишком сложным и вы в нём сами запутались. других объяснений я не нахожу :(

1. Если флуш вообще убрать - то вместо обещанного `ValueError` будет `pony.orm.core.CommitException: ValueError: a_i`
2. Если вставить глобальный `flush()` то будет таки `ValueError`

но документация говорит, что `commit` (пусть и не явный) делает внутри `flush()`. чё-то не сходится....

**Comment by socketpair** [comment]
насчёт `*_update()` не проверяли.

**Comment by kozlovsky** [comment]
Sorry for the inconvenience. As it turned out, the code of `obj.flush()` was not tested properly. Now all hooks should work correctly after `obj.flush()` as well as after the global `flush()` function. We will release 0.6.4. today with this fix.

**Comment by kozlovsky** [comment]
Done:
https://github.com/ponyorm/pony/releases/tag/0.6.4
https://pypi.python.org/pypi/pony/0.6.4

**Comment by socketpair** [comment]
Очень здОрово, что вы фиксите баги так быстро! Очень рад таки, а то у нас релз и под самый релиз такое дело.

А с видом исключения поведение пофикшено или так и будет как я описал в баге ?

**Comment by kozlovsky** [comment]
Я думаю что текущие баги с релизом - это просто "болезнь роста" - у нас сейчас резко возросло число core developers, работающих над Пони full time, и сейчас идет взаимная притирка. Ожидаю, что в ближайшее время появится и поддержка jsonb в PostgreSQL, и upserts, и много чего еще.

Что касается исключения, то оно будет успешно перехвачено. Поскольку `flush` в приведенном примере кода происходит явным образом за пределами `commit`, то исключение не будет обернуто в `CommitException`, а так и останется `ValueError`.

 Если сейчас речь о #159, чтобы никогда не обертывать исключения, происходящие во `flush`, в `CommitException`, то мы не могли сделать это в текущем hotfix-релизе, потому что такое изменение ломает обратную совместимость. Оно будет частью следующего релиза 0.6.5. Сейчас при необходимости можно явно вызывать `flush()` перед выполнением `commit` или выходом из `db_session`
