### ISSUE TITLE
to_dict handling of inheritance

### ISSUE THREAD

**Issue by danceasarxx** [ponyorm/pony#163]
to_dict is excluding an attribute that is on both entities that are children of `Person`

```python
class Person(data.Entity):
    firstname = Required(str)
    surname = Required(str)

class PatientInfo(Person):
    gakpid = Required(str, unique=True)
    kin = Optional('PatientKin')

class PatientKin(Person):
    patients = Set('PatientInfo')

with db_session:
    k = PatientKin(firstname='Oladapo', surname='Arewa')
    p = PatientInfo(firstname='Olakunle', surname='Arewa', kin=k, gakpid='121ssws112')
    p.to_dict(exclude='firstname',related_objects=True) # walked the related entities in real code
    # {'surname': 'Arewa', 'kin': {'surname': 'Arewa'}, gakpid: '121ssws112'}
```

**Comment by kozlovsky** [comment]
After executing
```python
    pprint(p.to_dict(exclude='firstname', related_objects=True))
```

I got the following dictionary:

```python
{'classtype': 'PatientInfo',
 'gakpid': u'121ssws112',
 'id': 2,
 'kin': PatientKin[1],
 'surname': u'Arewa'}
```

Looks correct to me. Why do you think that the result is wrong?

**Comment by danceasarxx** [comment]
Sorry, another false alarm....Turns out the function I am using to walk the related_objects path passes the options recursively. All this confusion is due to the fact I didn't know you use on table for inheritance(No joke, I should really read the docs more). Hope you aren't annoyed

**Comment by kozlovsky** [comment]
No problem, that's ok :) It is much better than to find some bug and not report it :)
