### ISSUE TITLE
pony.orm.dbapiprovider.OperationalError: (1054, "Unknown column 'User.password' in 'field list'")

### ISSUE THREAD

**Issue by zs1621** [ponyorm/pony#17]
when i init the database   and then   

```
 db.generate_mapping(create_tables=True)
```

it's ok
but,  after i modify the field add a new field
then   i  use 

```
db.generate_mapping(create_tables=True)
```

 i have the error

**Comment by franciscogimeno** [comment]
> Sometime later Pony will support automatic migrations, when ALTER TABLE command will generate automatically. I don't expect this to happen before end of August.
Hi @kozlovsky, any news on this functionality after 7 years?

I think it would be quite interesting having automatic migrations.
