### ISSUE TITLE
Prefetch lazy attribute?

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#172]
```python
db = Database()

class Post(db.Entity):
    title = Required(str, 128)
    text = Required(LongStr)

db.bind('sqlite', ':memory:')
db.generate_mapping(create_tables=True)
sql_debug(True)

with db_session:
    [Post(title=str(i), text='text {}'.format(i)) for i in range(5)]

with db_session:
    posts = Post.select().prefetch(Post.text)[:]
```

```sql
GET CONNECTION FROM THE LOCAL POOL
SWITCH TO AUTOCOMMIT MODE
SELECT "p"."id", "p"."title"
FROM "Post" "p"

SELECT "text"
FROM "Post"
WHERE "id" = ?
[1]

SELECT "text"
FROM "Post"
WHERE "id" = ?
[2]

SELECT "text"
FROM "Post"
WHERE "id" = ?
[3]

SELECT "text"
FROM "Post"
WHERE "id" = ?
[4]

SELECT "text"
FROM "Post"
WHERE "id" = ?
[5]

RELEASE CONNECTION
```

Why not

```sql
GET CONNECTION FROM THE LOCAL POOL
SWITCH TO AUTOCOMMIT MODE
SELECT "p"."id", "p"."title", "p"."text"
FROM "Post" "p"

RELEASE CONNECTION
```

?

**Comment by kozlovsky** [comment]
When `prefetch` method was added, the goal was not in minimizing SQL queries, but in loading all necessary data before exiting of `db_session`. Pony assumes that processing of any ORM objects take place inside `db_session`, but some users want to have the ability to read attribute values when the `db_session` is already over. So we added `prefetch` method which walks through the query result and preloads all specified attributes so they can be accessed later.

But you are right that prefetching can be optimized, at least in simple cases. So I just added an optimization which includes specified attributes into initial `SELECT`, if possible.
