### ISSUE TITLE
NotImplementedError: MySQL database provider does not support entities with composite primary keys inside aggregate functions

### ISSUE THREAD

**Issue by hfaran** [ponyorm/pony#185]
```python
NotImplementedError: MySQL database provider does not support entities with composite primary keys inside aggregate functions. Got: count(view)
```

Are there plans for this to be implemented? I'm attempting to switch from SQLite to MySQL, and it almost seems nightmare-ish (to clarify, I mean MySQL is; so many issues being seen with things that worked perfectly fine in sqlite :disappointed:).

**Comment by kozlovsky** [comment]
Sorry for long delay with the answer, I was overloaded on the prev week.

MySQL just don't support this type of queries, I don't think we can have some workaround here. But I think it is not necessary to have entities with composite primary key in MySQL. You can replace it with autoincrement primary key and composite secondary key. That is, refactor the entity

```python
class ExamMark(db.Entity):
    student = Required(lambda: Student)
    subject = Required(lambda: Subject)
    exam_date = Required(date)
    value = Required(int)
    PrimaryKey(student, subject, exam_date)
```
to the following entity:

```python
class ExamMark(db.Entity):
    id = PrimaryKey(int, auto=True)
    student = Required(lambda: Student)
    subject = Required(lambda: Subject)
    exam_date = Required(date)
    value = Required(int)
    composite_key(student, subject, exam_date)
```

This change should not have any effect to your application logic, and it should solve the issue with aggregate queries.

**Comment by hfaran** [comment]
I see. That is in fact the strategy I have been using to circumvent this in the meantime. It seems that it should work perfectly fine. Thanks!
