### ISSUE TITLE
What are the differences in performance between a composite_key and composite_index?

### ISSUE THREAD

**Issue by hfaran** [ponyorm/pony#187]
According to [the documentation] (https://docs.ponyorm.com/entities.html#composite-keys), composite keys can be used for uniqueness, and indices for speed.

My question is, if I have a `composite_key`, will it have the same speed benefits as a `composite_index`, or do I have to create both a `composite_key` and a `composite_index`?

Thanks.

**Comment by kozlovsky** [comment]
`composite_key` should be a bit faster then `composite_index`, but it assumes uniqueness of a composite key value. Both constructs should create indexes automatically, `composite_key` creates `UNIQUE INDEX`, and `composite_index` creates non-unique `INDEX`.

**Comment by hfaran** [comment]
Thanks for the info! Much appreciated.
