### ISSUE TITLE
Unbind the database in teardown

### ISSUE THREAD

**Issue by henri-hulski** [ponyorm/pony#214]
Is it possible to unbind the database?
I'm using Morepath and everything works really fine!
For testing I use py.test.
In the test I import `db` from the app model and in the test setup I bind the database.
```python
def setup_module(module):
    db.bind('sqlite', ':memory:')
    db.generate_mapping(create_tables=True)
```
When I do this in the next test I get the error
```
TypeError: Database object was already bound to SQLite provider`.
```
So I need to unbind the database in the teardown. Something like:
```python
def teardown_module(module):
    db.unbind()
```

**Comment by henri-hulski** [comment]
I found a solution.
```python
def setup_module(module):
    try:
        db.bind('sqlite', ':memory:')
    except TypeError:
        pass
    else:
        db.generate_mapping(check_tables=False)

    db.drop_all_tables(with_all_data=True)
    db.create_tables()

**Comment by ml31415** [comment]
I ran into similar issues experimenting around in the console. Imho there should be a clear cleanup mechanism for the database object. Mixing the connection and the schema definition is just a very bad idea.

**Comment by EtienneDesticourt** [comment]
For anyone who wishes to use the snippet above, note that `bind` now raises a `pony.orm.core.BindingError` and no longer a TypeError.

**Comment by fliiiix** [comment]
This is the fixture I use currently 
```
@pytest.fixture(scope="function")
def application():
    app.db.bind(provider="sqlite", filename=":memory:")
    app.db.generate_mapping(create_tables=True)

    yield app

    app.db.drop_all_tables(with_all_data=True)
    app.db.disconnect()

    app.db.provider = None
    app.db.schema = None
```

Is there still no better clean-up mechanism?
