### ISSUE TITLE
Lost DB connection when I use Pony for connect to the remote Postgres database. 

### ISSUE THREAD

**Issue by vmcfire** [ponyorm/pony#219]
Vasiliy Makaganchuk:
Hello everybody. I use Pony for connect to the remote Postgres database. Periodically, the database connection is lost and Pony returns an exception:

  File "... / lib / python2.7 / site-packages / pony / orm / core.py", line 1566, in close
    try: provider.rollback (connection, cache)
  File "<auto generated wrapper of rollback () function>", line 2, in rollback
  File "... / lib / python2.7 / site-packages / pony / orm / dbapiprovider.py", line 59, in wrap_dbapi_exceptions
    raise InterfaceError (e)
RollbackException: InterfaceError: connection already closed

After that, Pony automatic reconnect, but my function call is aborted.

Is it possible to test the connection and forced to reconnect? I have not found the necessary methods in Pony docs. Maybe you need to look at psycopg2 docs?

**Comment by vmcfire** [comment]
Alexander Kozlovsky:
Hi Vasiliy! Pony should be able to reconnect automatically, if the connection was lost not in the middle of transaction.

I think that your problem caused by the following sequense of actions:

1) An application code performs some query;
2) Due to some problem in configuration (for example, an insufficient size of some buffer) the server drops the connection, and Pony gets an exception from psycopg2;
3) Exception unrolling leads to exiting from db_session;
4) Pony tries to handle exit from db_session and attempts to peform rollback, assuming that the connection is stlii active;
5) At this moment we got another exception, "connection already closed" which masks previous exception.

I think we need to improve handling of rollback so it does not mask previous exception in case the connection is closed already.

Regarding your situation, I think the right way is not to attempt to reconnect, but to prevent an exception which lead to connection closing. After we fix handling of rollback, you should be able to see this original exception and will be able to fix its root

**Comment by kozlovsky** [comment]
Thanks for reporting, I fixed it. Previously the "connection already closed" exception masked the original exception which causes the connection closing. Now you can see the reason for connection closing, and if it is caused by some bug in Pony you can open another issue related to that specific problem.
