### ISSUE TITLE
Return foreign key value instead of object

### ISSUE THREAD

**Issue by lukashambsch** [ponyorm/pony#224]
I'm using pony w/ WTForms and I have a Form that contains a FormField which has a SelectField inside of it. In order for the data to populate correctly, it is expecting the values for the SelectField to be int instead of the objects.

So I have a supplier which has an address (supplier.addr). This address has a state (supplier.addr.state). Currently supplier.addr.state == State[4]. Is there any way for supplier.addr.state == 4?

I've searched the docs and I don't see anything, any help would be appreciated.

I've also tried setting the state to it's id manually, but it won't let me modify it.

When I set supplier.addr.state = supplier.addr.state.id, they value stays == State[4].

**Comment by kozlovsky** [comment]
Can you provide an example of your current code where you use SelectField with Pony?

**Comment by lukashambsch** [comment]
These are the forms. What I ended up doing was creating CustomSelectField to overrided WTForm's process_data function. But, it would still be helpful to know if there was an easier way.

`
class CustomSelectField(SelectField):
    def process_data(self, value):
        if value is None:
            self.data = None
        else:
            try:
                self.data = self.coerce(value.id)
            except (ValueError, TypeError):
                self.data = None

class AddressForm(WTForm):
    street_one = StringField('Street One', validators=[DataRequired()])
    street_two = StringField('Street Two', validators=[Optional()])
    city = StringField('City', validators=[DataRequired()])
    state = CustomSelectField('State', coerce=int)
    zip_code = StringField('Zip Code', validators=[Optional()])
    country = CustomSelectField('Country', coerce=int, validators=[DataRequired()])

class SupplierForm(Form):
    name = StringField("Name", validators=[DataRequired()])
    addr = FormField(AddressForm, label='')
`

**Comment by kozlovsky** [comment]
Why can you just pass `supplier.addr.state.id` as a value to `SelectField` instead of `supplier.addr.state`?

**Comment by lukashambsch** [comment]
The entire supplier obj is used to instantiate the SupplierForm values, so I'd have to modify that object. I tried this: 
```
supplier.addr.state = supplier.addr.state.id
```
before instantiating the form, but it didn't have any affect.
