### ISSUE TITLE
Broken link on web page

### ISSUE THREAD

**Issue by MortalCatalyst** [ponyorm/pony#225]
The entities documentation page https://docs.ponyorm.com/entities.html refers to more examples.
[https://github.com/ponyorm/pony/blob/orm/pony/orm/examples/university.py](https://github.com/ponyorm/pony/blob/orm/pony/orm/examples/university.pyl)

However the link returns a 404.

**Comment by amalashkevich** [comment]
Thank you for reporting. Should be fixed now.
