### ISSUE TITLE
Access prior value in before_update

### ISSUE THREAD

**Issue by lukashambsch** [ponyorm/pony#233]
I have an item with quantity_received and each time that field is updated I need to increase or decrease the quantity in another table. Is there any way to access the previous value in before_update?

I thought I would be able to in before_update since the save hasn't been committed yet.

Something like this:

```
class Item(db.Entity):
    quantity_received = Optional(int, default=0)
    product = Required(Product)

    def before_update(self):
        prev_qty = get_previous_value_here()
        warehouse_product = WarehouseProduct.get(product=self.product)
        warehouse_product.quantity += (self.quantity_received - prev_qty)
```

I didn't see any obvious way to do it when looking at the docs. Any suggestions?

**Comment by lukashambsch** [comment]
After reading further it looks like I need a way to clear what Pony is caching so that I can get the value that is currently in the db. Does anyone know how to do this?

**Comment by kozlovsky** [comment]
At this moment Pony doe snot have an official way of obtaining previous attribute value, but you can write the following function:

```python
from pony.orm import core

def get_prev_value(obj, attr_name):
    attr = getattr(obj.__class__, attr_name)
    assert isinstance(attr, core.Attribute)
    dbval = obj._dbvals_.get(attr)
    return attr.converters[0].dbval2val(dbval)
```

Then you can write:
```python
    def before_update(self):
        prev_qty = get_prev_value(self, 'quantity_received')
```

The `get_prev_value` function will return the value which Pony is considered as currently stored in the database (if no other transaction rewrites it). But I don't think you should rely on any such function. It is much safer to explicitly store previous value when you retrieve an object from the database:

```python
prev_values = {}  # this dict should be local to current db_session
item = Item[123]
prev_values[item, 'quantity_received'] = item.quantity_received
```
After that you can check the value in this dict during `before_save`

**Comment by lukashambsch** [comment]
Thanks! Since the value is being changed on the client, I decided to use the get_prev_value function. It is working great. Thanks again!
