### ISSUE TITLE
Something confusing in the docs

### ISSUE THREAD

**Issue by odarbelaeze** [ponyorm/pony#234]
Hi,

I heard from the project in talk python to me, and its awesome I like it a lot, I prompted one of my students to use pony in one teaching project, as I was reading throuhg the docs I kept seign the `select`, `count`, etc... methods beign used, but no imports I tried `from pony import select` and that didn't work then I tried `from pony.orm import select` and that was better, now, reading the quickstart guide I se that the docs assume you'll do:
```
from pony.orm import *
```
I personally dislyke this kind of imports since I use python in kind of a wide stack and name clashes wouldn't be rare, I know linters dont like them either.

Would you kindly modify your docs so that it's clear where the methods come from and how one can import each method individually.

Let me know if you'd need help with this and I'll be happy to bring it up fron.

Cheers,

Oscar

**Comment by micaiahparker** [comment]
On a large project where I'm worried about name clashes I typically do:

`from pony import orm`

**Comment by odarbelaeze** [comment]
We should put that somewhere close to the api docs [here](https://docs.ponyorm.com/api_reference.html#entity-methods) it states all the methods and classes available, but not where they are in the package 😅
