### ISSUE TITLE
Add support for PostgreSQL arrays

### ISSUE THREAD

**Issue by effulon** [ponyorm/pony#243]
I saw it mentioned in an old issue that this was a planned feature. Any news on support for integer and text arrays?

**Comment by amalashkevich** [comment]
One of the possible ways of storing data as arrays is using [Pony JSON support](https://docs.ponyorm.com/json.html). Does it work for you?

**Comment by effulon** [comment]
I was hoping to use Pony to query a database made with [discogs-xml2db](https://github.com/philipmat/discogs-xml2db), rather than store data of my own (see create_tables.sql for the schema). Am I right in thinking that's not possible?

**Comment by kozlovsky** [comment]
Hi, at this moment integer and text arrays are not supported yet. So right now if you want to use discogs-xml2db, you need to use another query tool. Having JSON support it is not too hard to add support of PostgreSQL arrays, but other tasks have higher priority right now

**Comment by Freewolny** [comment]
I think it is fixed now in https://github.com/ponyorm/pony/commit/6e041aa766652ccd901a17878526eb79fa8a97eb, should it be closed then?

**Comment by kozlovsky** [comment]
You are right, thanks
