### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by luckydonald** [ponyorm/pony#248]
```
Sorry, but pony 0.7.1 requires Python of one of the following versions: 2.7, 3.3-3.6.
You have version 3.7.0a0
```
https://travis-ci.org/luckydonald/pbft/jobs/214432324#L165

**Comment by kozlovsky** [comment]
Python 3.7 development is just started recently. This is the preliminary release schedule:

3.7 development begins: 2016-09-12
3.7.0 alpha 1: 2017-09-11
3.7.0 alpha 2: 2017-10-16
3.7.0 alpha 3: 2017-11-13
3.7.0 alpha 4: 2017-12-18
3.7.0 beta 1: 2018-01-29 (No new features beyond this point.)
3.7.0 beta 2: 2018-02-26
3.7.0 beta 3: 2018-03-26
3.7.0 beta 4: 2018-04-30
3.7.0 candidate 1: 2018-05-21
3.7.0 candidate 2: 2018-06-04 (if necessary)
3.7.0 final: 2018-06-15

Python 3.7 adds two new bytecodes we need to add to decompiler: `LOAD_METHOD` and `CALL_METHOD`. Maybe another new bytecodes will be added later. I don't think we should declare support of Python 3.7 at this moment, let's wait for alpha 1 release at least.

**Comment by johnnywell** [comment]
There is any movement on this?

**Comment by kozlovsky** [comment]
Support of Python 3.7 just added in af9645e3
