### ISSUE TITLE
keys query func

### ISSUE THREAD

**Issue by pingf** [ponyorm/pony#254]
```
    configs = select(c for c in SpiderConfig if 'agent' in c.config.keys)[:]
```

is there a query func that support something like above, the config is the jsonb in pg

**Comment by pingf** [comment]
from here() I can see , in pg, you can do
```
select key_exists('{"key_a": {"nested_key": "a"}, "key_b": {"nested_key": "b"}}'::json, 'key_a');
```
is there any way I can do this in pony?

**Comment by zdereli** [comment]
Assuming `SpiderConfig .config` has a value like `{"agent": {...}, "operators": [....]}`, you can already do that:
```
    configs = select(c for c in SpiderConfig if 'agent' in c.config)[:]
```

without using `.keys`.

**Comment by pingf** [comment]
thx a lot :+1:

**Comment by pingf** [comment]
another problem, 
actually I want to check multiple keys in the config, is there any simple way ?

**Comment by kozlovsky** [comment]
If keys are known in advance, you can test several keys in the following way:
```python
query = select(c for c in Config if 'foo' in c.config and 'bar' in c.config)
```
If key values become known at runtime, you can make a loop and call `filter` method of a query:
```python
query = select(c for c in Config)
keys = ['foo', 'bar']
for key in keys:
    query = query.filter(lambda c: key in c.config)
```
