### ISSUE TITLE
Order by with NULLS last

### ISSUE THREAD

**Issue by lukashambsch** [ponyorm/pony#263]
Is there a way to call order_by on a query and place the nulls last for the ascending sort?

For non nested fields I am able to just use the string parameter and prefix it with a minus sign.

```
models.Inventory.select().order_by('desc(-i.quantity)')
```

However this doesn't work for nested ordering.

```
models.Inventory.select().order_by('desc(-i.product.sku)`)
```

I am hoping that I am missing something in the docs and that there is a simple way to do this w/ Pony. Thanks!

**Comment by kozlovsky** [comment]
Hi, what database do you use?

**Comment by lukashambsch** [comment]
I'm using MySQL.

**Comment by kozlovsky** [comment]
I think the second query does not work not because of nesting, but because the the type of field is text, and Pony does not know about that undocumented MySQL feature that allows to apply unary minus to all columns, including text columns.

Try the following, it should work for all databases:

```python
models.Inventory.select().order_by('''
    1 if i.quantity is None else 0, i.quantity
''')

models.Inventory.select().order_by('''
    1 if i.product.sku is None else 0, i.product.sku
''')
```

**Comment by lukashambsch** [comment]
That seems to work. Thanks!

I really appreciate you getting back to me so quickly!

**Comment by jorenvh1** [comment]
Hey @kozlovsky 
Could you explain how to make this work using the desc() function? For default ascending sorting it works, but when using desc() around it, it's throwing an error because it's treating the parts separated by the comma as function parameters...

**Comment by jorenvh1** [comment]
> Hey @kozlovsky Could you explain how to make this work using the desc() function? For default ascending sorting it works, but when using desc() around it, it's throwing an error because it's treating the parts separated by the comma as function parameters...

I've fixed this by splitting up the order_by's. One for the expression, and another for the field itself.
