### ISSUE TITLE
Add handler to "pony.orm" logger does not work

### ISSUE THREAD

**Issue by sio2sio2** [ponyorm/pony#266]
if a handler is added a "pony.orm" logger, pony continues to print on the screen for debugging. I think it's fixed by replacing the line:

`if logging.root.handlers:`

with:

`if orm_logger.hasHandlers():`

or

` if sql_logger.hasHandlers():`

in **pony.orm.core.log_orm()** and **pony.orm.core.log_sql()** functions.

**Comment by kozlovsky** [comment]
Thanks, should work now
