### ISSUE TITLE
How to disable optimistic check?

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#267]
I have code like this:

```python
def before_request():
    if (datetime.utcnow() - current_user.last_visit).total_seconds() >= 60:
        current_user.last_visit = datetime.utcnow()
```

Because this code executes for every http request and http requests may be concurrent, it sometimes raises `Object User[n] was updated outside of current transaction`. But this check is not necessary for last_visit field: if this value is a little wrong, nothing bad will happen for my case. Is this possible to disable optimistic check here?

(Using memcache for last_visit or something like this looks like good workaround, but I want my application to work without it.) (Pessimistic locking is bad workaround :)

**Comment by Vitalium** [comment]
Try to use `volatile=True` parameter in field definition to avoid "... updated outside of current transaction".

**Comment by andreymal** [comment]
It works, thanks 👍

I tried to find an option in documentation by searching for the keyword "optimistic", but did not find anything

**Comment by amalashkevich** [comment]
@Vitalium thanks for your comment. Added this info to the [Optimistic concurrency control](https://docs.ponyorm.com/transactions.html#optimistic-concurrency-control) paragraph.
