### ISSUE TITLE
Using min or max function on field w/ no values throws TypeError

### ISSUE THREAD

**Issue by lukashambsch** [ponyorm/pony#269]
When running the following code, I receive TypeError: a float is required:

```
field_min = math.floor(pony_min(getattr(c, field) for c in self.model))
```

The error is thrown because each database row has None as the value for field. I think it would be better to return None in this case rather than throwing an error.

**Comment by kozlovsky** [comment]
If I understand correctly, you just should not pass `None` to `math.floor` function. Try to rewrite the code in the following way:

```python
field_min = pony_min(getattr(c, field) for c in self.model)
field_min = math.floor(field_min if field_min is not None or 0)
```

**Comment by lukashambsch** [comment]
Got it, I thought it was the min function throwing the error. Thanks!
