### ISSUE TITLE
How to define a no primarykey entity?

### ISSUE THREAD

**Issue by sail1972** [ponyorm/pony#279]
I have a table there's no id and primary key. How to map it to entity in PonyORM?
When I define it like bellow:
```python
class SaleRecord(db.Entity):
    _table_ = "B2I_SALE_RECORDS"
    saleman_mobile_number = Required(str, 11)
    user_contact_number = Required(str, 11)
    user_mobile_number = Optional(str, 11)
    sale_log_time = Required(datetime, 6)
```
raise an error：
```
  File "/home/sail/projects/microApp_test/venv/local/lib/python2.7/site-packages/pony/orm/dbapiprovider.py", line 55, in wrap_dbapi_exceptions
    except dbapi_module.DatabaseError as e: raise DatabaseError(e)
pony.orm.dbapiprovider.DatabaseError: ORA-00904: "B2I_SALE_RECORDS"."ID": invalid identifier
```

**Comment by sashaaero** [comment]
Actually you cannot do that. Pony requires each entity to have a primary key. It's not unique to Pony. Each ORM [has](https://stackoverflow.com/questions/19243990/doctrine-table-without-primary-keys) [the](https://stackoverflow.com/questions/8591255/hibernate-without-primary-key) [same](https://stackoverflow.com/questions/28516086/can-i-create-model-in-django-without-automatic-id) [rule](https://stackoverflow.com/questions/34283259/how-to-define-a-table-without-primary-key-with-sqlalchemy).

By the way, primary key shouldn't be `id` only. You can specify it as composite key of some unique combination of attributes. See [this issue](https://github.com/ponyorm/pony/issues/272) for details.

**Comment by sail1972** [comment]
I see, Thanks a lot.
`B-)
