### ISSUE TITLE
Lost Json Update

### ISSUE THREAD

**Issue by jamesstidard** [ponyorm/pony#283]
I noticed I was loosing some updates during writing to a Json attribute. I guess the Json attribute doesn't get marked as dirty when modifying.

Here's an example ('foo' is lost):

```python
from pony.orm import *

db = Database()
db.bind('sqlite', filename=':memory:', create_db=True)


class Person(db.Entity):
    name = Required(str)
    body = Optional(Json, default={})


db.generate_mapping(create_tables=True)


with db_session:
    p = Person(name='Bort', body={'qux': 'baz'})
    flush()
    pid = p.id
    show(p)
    p.name = 'terry'
    p.body['foo'] = 'bar'
    commit()
    show(p)

with db_session:
    p = Person[pid]
    show(p)
```

**Comment by kozlovsky** [comment]
Thanks for reporting, your example should work now.

But the following examples will not work:

```python
data = {'age': 20}
p = Person(name='John')
p.body = data
data['tel'] = '123-45-67'

items = ['foo', bar]
p = Person(name='Mike')
p.body = items
items.append('baz')
```

In these examples, Json field will not get changes made after the attribute assignment, because the value of attribute is copied on assignment now. The correct code looks like this:
```python
data = {'age': 20}
p = Person(name='John')
p.body = data
p.body['tel'] = '123-45-67'

items = ['foo', bar]
p = Person(name='Mike')
p.body = items
p.body.append('baz')
```

**Comment by jamesstidard** [comment]
@kozlovsky Thanks a lot for taking a look and fixing this. This works just on the top-level object, right?

For example this wouldn't work either, right?

```python
data = {'contact_details': {}}
p = Person(name='John')
p.body = data
p.body['contact_details']['tel'] = '123-45-67'
```

**Comment by kozlovsky** [comment]
Now it should work for arbitrary nested objects too =)

**Comment by jamesstidard** [comment]
@kozlovsky Very nice. Thanks again.
