### ISSUE TITLE
Enchantment: Pagination

### ISSUE THREAD

**Issue by kickapoo** [ponyorm/pony#287]
Currently Ponyorm support the `Query.page` (https://docs.ponyorm.com/api_reference.html#Query.page) but in most cases this is not enough. 

A very simple examples is a typical web application that needs to return a list of object and paginate on objects for table view.

Most of other orms offer a `has_next`, `has_previous` in the return object list for this. 

Please consider another method in the Query that offer a more practical approach.

**Comment by andreymal** [comment]
I think this is not ORM task. I just use Paginator from Django (adapted for my cases)

**Comment by xr09** [comment]
+1 I'd love this getting implemented, had to create an annoying hack to emulate this helper.

https://stackoverflow.com/questions/43234918/pagination-with-pony-orm

**Comment by kickapoo** [comment]
https://docs.ponyorm.com/working_with_entity_instances.html#limiting-the-number-of-selected-objects

> You can also use the Query.page() method
