### ISSUE TITLE
AttributeError: module 'symbol' has no attribute 'list_for' with Python 3

### ISSUE THREAD

**Issue by lukashambsch** [ponyorm/pony#288]
I'm in the process of upgrading our app to use Python 3. Specifically I'm using Python 3.6.2. While making this upgrade I started getting this error (AttributeError: module 'symbol' has no attribute 'list_for') when running the following line of code:

`items = items.filter('i.id in [2]')`

Is there a different way I should be writing this query to work with Python 3? I need to use the string query format so that I can build the query as a part of our api.

**Comment by kozlovsky** [comment]
Thanks for reporting, should work now!

**Comment by lukashambsch** [comment]
Awesome! Thanks for the quick fix!
