### ISSUE TITLE
Real stack traces swallowed within python shells

### ISSUE THREAD

**Issue by ml31415** [ponyorm/pony#294]
Just getting started with ponyorm, experimenting around with IPython, I ran into the first minor annoyance. Any issue and stack trace is swallowed within pony:

```
/usr/local/lib/python2.7/dist-packages/pony/utils/utils.pyc in cut_traceback(func, *args, **kwargs)
     72                 tb = tb.tb_next
     73             if last_pony_tb is None: raise
---> 74             if tb.tb_frame.f_globals.get('__name__').startswith('pony.utils') and tb.tb_frame.f_code.co_name == 'throw':
     75                 reraise(exc_type, exc, last_pony_tb)
     76             reraise(exc_type, exc, full_tb)

AttributeError: 'NoneType' object has no attribute 'startswith'
```

`__name__` is not set in a prompt, mb simply adding '' as default for the `get` would do already.

**Comment by kozlovsky** [comment]
Thanks for reporting! Should work now. If you will encounter another shell issues, please report them too.
