### ISSUE TITLE
Query returning smallest not largest query results

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#297]
I'm currently trying to return a list of users by what letter their username starts with.  

```
q = request.args.get('q')    
query = models.select(u for u in models.User if u.username.startswith(q)).order_by(lambda u: len(u.followers)).limit(10)

```
But for some reason this returns users with 0 followers, instead of the top 10 for what ever the q is

**Comment by Vitalium** [comment]
Did you try count(u.followers) instead of len?

**Comment by nadermx** [comment]
Yes, trying 
`models.select(u for u in models.User if u.username.startswith(q)).order_by(lambda u: models.count(u.followers)).limit(10)`

yields the same results, with postgres and pony

**Comment by kozlovsky** [comment]
By default SQL uses ascending order (from smallest to largest values). If you want to place users with most followers at the top, you need to use `desc` for descending order:

```python
query = models.select(
    u for u in models.User if u.username.startswith(q)
).order_by(
    lambda u: desc(len(u.followers))
).limit(10)
```

**Comment by nadermx** [comment]
Thank you, that fixed it
