### ISSUE TITLE
PostgreSQL uuid & hstore types

### ISSUE THREAD

**Issue by sublimator** [ponyorm/pony#3]
This project looks fantastic :)

I grepped for `uuid` in the examples, yet found no instances.

Would love to see support / examples.

Where's the buy now :) ?

**Comment by tonycpsu** [comment]
+1, this would be excellent.

**Comment by rikuayanokozy** [comment]
https://github.com/ponyorm/pony/pull/165
I added list/jsonb converter.

**Comment by kozlovsky** [comment]
We added support of `jsonb` type in PostgreSQL as well as equivalent types for other databases in [PonyORM 0.6.6](https://docs.ponyorm.com/json.html). It seems that `jsonb` type is superior to `hstore`, so it is not necessary to add `hstore` support except for working with legacy database schemas. For that reason I close this issue.
