### ISSUE TITLE
Multiphase entity mapping

### ISSUE THREAD

**Issue by NiklasRosenstein** [ponyorm/pony#302]
I'm creating an application that has a core and pluggable components. The pluggable components may define additional database entities. The component's entity definitions may change from one version to another, and thus the components provide a functionality to migrate from a previous to a new version of the entity definition.

The previously used version of the component is also stored in the database and managed by the *core* component. The problem is that in order to find out if a component's entity definition changed, I'll have to check the `ComponentDatabaseRevision` entity, but this is not possible if `db.generate_mapping()` fails. And it can easily fail when an entity of a component has a new column.

I've tried to generate the mapping, and only *then* load the components, but then subclassing `db.Entity` fails. And I'm guessing that calling `db.generate_mapping()` a second time after the components have been loaded would fail as well.

Is there a way to generate the mapping only for a specific entity first, and only later generate the mapping for all remaining entities? Something like this maybe:

```python
db.generate_mapping(create_tables=True, entities=[ComponentDatabaseRevision])

with db_session():
  for comp in components:
    rev = ComponentDatabaseRevision.get(name=comp.name)
    if rev and rev.num != comp.database_revision:
      # Migrate schema of component

db.generate_mapping(create_tables=True)
```

**Comment by kozlovsky** [comment]
Currently Pony doesn't allow defining new entities after `db.generate_mapping` was called.

In your case you can create two different `Database` objects connected to the same database. One database object will be used to retrieve the revision information, while another database object will be used to work with components:

```python
# define entities with information about revisons
def define_revision_component(db):
    class ComponentDatabaseRevision(db.Entity):
        name = Required(str)
        num = Required(int)
        ...

# create db object to retrieve revision information
def get_revision_db(**db_params):
    db = Database()
    define_revision_component(db)
    db.bind(**db_params)
    db.generate_mapping(create_tables=True)
    return db

# define entities for components
def define_other_components(db):
    class Foo(db.Entity):
        a = Required(int)

    class Bar(db.Entity):
        b = Optional(str)

# create db_object for working with components
def get_main_db(**db_params):
    db = Database()
    # uncomment the next line if you want:
    # define_revision_component(db)
    define_other_components(db)
    db.bind(**db_params)
    db.generate_mapping(check_tables=False)
    return db

# the next two db objects connects to the same physical database
revision_db = get_revision_db(**settings.db_params)
main_db = get_main_db(**settings.db_params)

with db_session:
    for comp in components:
        rev = revision_db.ComponentDatabaseRevision.get(name=comp.name)
        if rev and rev.name != comp.database_revison
            # Migrate schema of component

with db_session
    select(foo for foo in main_db.Foo if foo.a == 'hi')
```

Note that you can define entities inside a function, it can be useful to define the same entties in multiple database objects. Also, after you define MyEntity(db.Entity) class, you can access it as a property of `db` object: `db.MyEntity`

**Comment by NiklasRosenstein** [comment]
Thanks! Both, defining entities inside a function and creating a separate Database object did the trick for me. :)
