### ISSUE TITLE
Frozenset?

### ISSUE THREAD

**Issue by tschm** [ponyorm/pony#306]
This is a query I use to select all fields that are of type BB static or BB dynamic:

`    x = [name for name in select(f.name for f in Field if f.type.name in set({'BB-static', 'BB-dynamic'}))]`

Good Python suggests to remove the set() construct and go directly with {...}. I am running Python 3.6.
However, then {} is a frozenSet and pony fails.

**Comment by Vitalium** [comment]
Why not to use list [] or tuple ()?

```python
x = [name for name in select(f.name for f in Field if f.type.name in ['BB-static', 'BB-dynamic'])]
```

**Comment by sashaaero** [comment]
Thanks for reporting, tschm. Fix is already on github.
Now it should work.
