### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#307]
I currently have a model with json in it, I'm trying to verify the value of the key

```
class Payment(db.Entity):
    user = Optional(lambda: User)
    payed = Optional(Json)

payments = select(p for p in models.Payment if p.payed)
for p in payments:
    if 'subscr_signup' in p.payed['ipn']['txn_type']:

```
But it errores out
```
Traceback (most recent call last):
  File "fix_payments.py", line 84, in <module>
    if 'subscr_signup' in p.payed['ipn']['txn_type']:
KeyError: 'txn_type'

```

How would I check the value of the json in the model?

**Comment by kozlovsky** [comment]
Hi Johnathan! What database do you use?

**Comment by kozlovsky** [comment]
After you retrieved an object from the database, the JSON field may contains dictionaries and lists with a standard Python API. You can modify the check in the following way:
```python
for p in payments:
    ipn = in p.payed['ipn]
    if 'txn_type' in ipn and 'subscr_signup' in ipn['txn_type']:
        ...
```
or use something like that:
```python
for p in payments:
    if 'subscr_signup' in p.payed['ipn'].get('txn_type', {}):
        ...
```

**Comment by nadermx** [comment]
Postgres, and it appears sthe workaround worked.  Thank you
