### ISSUE TITLE
JSON Value Assignment Broken in v0.7.3

### ISSUE THREAD

**Issue by SPARTAN563** [ponyorm/pony#308]
With the release of v0.7.3 we are seeing a number of failures with the following error when attempting to assign values to JSON properties on our models.

```
src\app\lib\db_store.py:134: in update
    setattr(maint, key, val)
<string>:2: in __set__
    ???
..\..\python36-32\lib\site-packages\pony\utils\utils.py:58: in cut_traceback
    return func(*args, **kwargs)
..\..\python36-32\lib\site-packages\pony\orm\core.py:2120: in __set__
    new_val = attr.validate(new_val, obj, from_db=False)
..\..\python36-32\lib\site-packages\pony\orm\core.py:2352: in validate
    val = Attribute.validate(attr, val, obj, entity, from_db)
..\..\python36-32\lib\site-packages\pony\orm\core.py:2027: in validate
    val = converter.validate(val, obj)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

converter = <pony.orm.dbproviders.sqlite.SQLiteJsonConverter object at 0x0453C750>
val = {}, obj = OurModel['000000000000000000']

    def validate(converter, val, obj=None):
        if obj is None or converter.attr is None:
            return val
>       if isinstance(val, TrackedValue) and val.obj is obj and val.attr is converter.attr:
E       AttributeError: 'TrackedDict' object has no attribute 'obj'
```

Looking at the code, it appears that this was introduced as part of the fix for #283 and is simply a matter of the wrong property being used [here](https://github.com/ponyorm/pony/blob/orm/pony/orm/dbapiprovider.py#L771) to reference [this](https://github.com/ponyorm/pony/blob/orm/pony/orm/ormtypes.py#L225).

## Code that generates this error
```python
from pony import orm
from pony.orm import db_session
from uuid import uuid4

db = orm.Database()
class OurModel(db.Entity):
  id = orm.PrimaryKey(str, default=lambda: uuid4().hex)
  data = orm.Required(orm.Json)

id = uuid4().hex
with db_session:
  # This is OK
  entity = OurModel(id=id, data={})
  db.commit()

with db_session:
  entity = OurModel[id]
  entity.data = {"test": True} # This throws an exception
```

**Comment by kozlovsky** [comment]
Thanks for reporting!

Actually, the only way to reproduce the bug is to assign the attribute value to the same attribute:
```python
obj.json_attr = obj.json_attr
```

**Comment by SPARTAN563** [comment]
Ah, you're absolutely correct, sorry that I missed that in the repro code.

**Comment by Vitalium** [comment]
That's not all. There is another related bug. While trying to change loaded entity object several times, it is raised exception: pony.orm.dbapiprovider.InterfaceError: Error binding parameter ## - probably unsupported type.

There is a workaround - to set Json field volatile.

I'm trying now to write a code to reproduce this issue and add it later.

**Comment by Vitalium** [comment]
Unfortunately, I can't reproduce this error, but I found out that it happens when entity attributes has been changed outside current transaction. When inside `core.py` in `_save_modified_()` function `where` conditions extends by optimistic attributes and its values, some values isn't converted to appropriate type, in this case TrackedDict isn't converted to json-serialized string.

**Comment by kozlovsky** [comment]
@Vitalium what database are you using?

**Comment by Vitalium** [comment]
SQLite

**Comment by kozlovsky** [comment]
Thanks @Vitalium! I was able to reproduce and fix the bug that you reported!

**Comment by Vitalium** [comment]
Beautiful! :) Thank you!

**Comment by steelliberty** [comment]
I am getting 
InterfaceError: Error binding parameter 2 - probably unsupported type.
Error binding parameter 2 - probably unsupported type.

with version 7.3 while running 7.2 mode code runs without and error. 

I am doing a Json assignment  -- This is happening in numerous places in the code -- but for example the simplest case is : 

class NewsFeeds(newsfeeds.Entity):
    id = PrimaryKey(int, auto=True)
    feedinfo = Optional(Json, default = {})
    hashlist = Optional(Json, default=[])
    feedlist = Optional(Json, default = {})
    feeds = Optional(Json, default = {})

 @classmethod
 @db_session
    def addHashCode(cls,h):
        nf = NewsFeeds.get(id=1)
        if nf:
            nf.hashlist.append(h)
            commit()

The same code in 7.2 works everytime .. there are other places that blow up in the full code -- sometimes the assignment above works but then later another one fails. 

I can see nothing that explains this .. 

Any thoughts ?
