### ISSUE TITLE
How to use a separate database for testing?

### ISSUE THREAD

**Issue by sloria** [ponyorm/pony#32]
I am trying to integrate Pony with Flask-Testing (unsuccessfully, so far--see #25 )--and I'm wondering how I can use a separate database for testing. In Flask-SQLAlchemy, for example, this would be achieved by setting the `SQLALCHEMY_DATABASE_URI` config option in the test setup

``` python
from flask.ext.testing import TestCase
from app import app
class TestApp(TestCase):
    TESTING = True
    DEBUG = True
    SQLALCHEMY_DATABASE_URI = 'sqlite:///tmp/test.db'

    def create_app(self):
        app.config.from_object(self)
        return app
```

I am not sure how to achieve this with Pony, since each `Entity` class must be declared from a `Database` that is already configured.

**Comment by larsks** [comment]
> Although it is possible to add the database URI support in the SQLAlchemy-compatible way, right now I don't see the point in it.

Supporting database URIs makes it much easier to provide database connection information in a simple configuration file.  For example, if I have a simple ConfigParser INI-style configuration, I could do something like this during development:

```
[my_app]
dburi = sqlite:///mydatabase.db
```

And something like this during testing:

```
[my_app]
dburi = postgresl://appuser:password@remotehost/database
```

It allows the connectivity information to be provided trivially from the command line as well.

**Comment by kozlovsky** [comment]
I agree, I think we need to add database URIs

**Comment by gaozhidf** [comment]
**models/brands.py**
```python
from config.settings import DB_CONFIG
from pony.orm import *

db = Database()
db.bind(provider='mysql', **DB_CONFIG)
set_sql_debug(False)


class Brands(db.Entity):
    _table = 'brands'
    id = PrimaryKey(int, size=64, unsigned=True)
    country_id = Optional(int, default=0)

db.generate_mapping(create_tables=False)
```

**test_api.py**
```python
class ApiTestCase(unittest.TestCase):
    def fake_db(self):
        from models.brands import db
        from pony.orm import Database
        self.db_fd, self.db_fp = tempfile.mkstemp()
        new_db = Database(provider='sqlite', filename=self.db_fp)
        new_db.entities = db.entities
        new_db.generate_mapping(create_tables=True)
        db.provider = new_db.provider
        db.schema = new_db.schema
        self.db = db

    def setUp(self):
        with mock.patch('models.brands.db.bind', new_callable=self.fake_db):
            self.app = api_server.app.test_client()

    def test_get_brands(self):
        rsp = self.app.get('/api/brand/')
        print(str(rsp.json))

    def tearDown(self):
        # self.db.drop_all_tables(with_all_data=True)
        os.close(self.db_fd)
        os.remove(self.db_fp)
```

it mays a trick one, and mocks **db.bind** when it was called
