### ISSUE TITLE
Missing exception, forgot to inherit from db.Entity

### ISSUE THREAD

**Issue by AbornDK** [ponyorm/pony#320]
It cast NotImplementedError, i belive there should be an exception for this, and we spend quite a while spotting this error. I can submit a code example if required.

**Comment by sashaaero** [comment]
Hello! Thanks for reporting. Can you show the code which produces this error?
Because 
```python
>>> from pony.orm import *
>>> db = Database('sqlite', ':memory:')
>>> class A(db.Entity):
...     a = Required(int)
...
>>> class B():
...     a = Required(int)
...
>>> class C(B):
...     b = Required(int)
...
>>> db.generate_mapping(create_tables=True)
```
Because this code does not produce any errors.

**Comment by AbornDK** [comment]
Trying to reproduce it, i found it also cast (Entity not found 'myclass'). So the NotImplementedError is not a problem anyways, it was caused by the generate_mappping failing, and still trying to run the next test.

Case closed sorry for your time.
