### ISSUE TITLE
KeyError on delete

### ISSUE THREAD

**Issue by lukashambsch** [ponyorm/pony#321]
When trying to delete an item from the database, I am receiving a KeyError. This is part of the stack trace:

```
File "<string>", line 2, in delete
File "/home/ec2-user/.env/src/pony/pony/utils/utils.py", line 81, in cut_traceback
  return func(*args, **kwargs)
File "/home/ec2-user/.env/src/pony/pony/orm/core.py", line 4539, in delete
  obj._delete_()
File "/home/ec2-user/.env/src/pony/pony/orm/core.py", line 4506, in _delete_
  obj2 = cache_index.pop(vals)
KeyError: (Order[100330699], 'AD-UNI-SMPGRP-08')
```

It seems the KeyError is sending me values that are part of the composite_key. Why would this be a key error on a delete?

**Comment by lukashambsch** [comment]
This is causing an issue in our production system. Is there a workaround?

I've tried using a delete statement using execute, but that causes an error later in the code when trying to create another object with the same composite key as the deleted object.

**Comment by kozlovsky** [comment]
At this moment I don't fully understand what may be the reason for the error and how to reproduce it. Can you show model definitions or send them privately? Also, you write that you delete object and immediately create a new objects with the same key. Are you sure this is necessary? Maybe it is better to just update the previous object?

**Comment by lukashambsch** [comment]
Removing the delete entirely was my first thought too. It's some old code that doesn't have any testing in place, so I'm hesitant to just remove it entirely. I'm afraid of corrupting the data. I can share the model definition privately. How would you like me to send them?

**Comment by kozlovsky** [comment]
You can send them to my email alexander.kozlovsky@gmail.com

**Comment by kozlovsky** [comment]
Thanks for the reporting, we were able to reproduce and fix the problem
