### ISSUE TITLE
Escape dollar sign when running with execute

### ISSUE THREAD

**Issue by lukashambsch** [ponyorm/pony#322]
When running a db query with db.execute, how do I escape the dollar sign at the beginning of a value? I've tried preceding the dollar sign with a backslash, but that seems to be generating the same error. Here is the error I'm receiving:

`NameError: name 'tre' is not defined`

I get this value when trying to insert `$tre` with an insert statement.

**Comment by sashaaero** [comment]
Hello! Could you show the code which produces this error?

**Comment by lukashambsch** [comment]
First, I'm building a query string. Then I'm executing the sql statement:
```
fields = dict_list[0].keys()
fields_str = ','.join(fields)
values = [[utils.replace_second_character(pymysql.escape_dict(d, 'utf-8')[f], '$', '\$')
               for f in d] for d in dict_list]
value_strings = ['({})'.format(','.join(v)) for v in values]
updates = ['{table}.{field} = VALUES({table}.{field})'.format(table=table, field=f) for f in fields]
update_string = ', '.join(updates)
query = '''
        INSERT INTO {table} ({fields_str})
        VALUES {insert_values}
        ON DUPLICATE KEY UPDATE
        {update_string}
    '''.format(table=table, fields_str=fields_str, insert_values=', '.join(value_strings), update_string=update_string)
db.execute(query).fetchall()
```

In the values part of the query string there is a value that begins w/ a dollar sign ('$tre'). Since this is the same syntax that pony uses for the sql query formatting, it is throwing that error because there is no tre variable passed in.

**Comment by kozlovsky** [comment]
Hi Lukas!

It is not safe to directly interpolate parameters into query string, because it can lead to [SQL injection](https://en.wikipedia.org/wiki/SQL_injection). With Pony you can use $ sign before Python variable name or expression placed inside the SQL query, and Pony automatically create a proper query parameter which prevents SQL injections:

```python
a, b, c = 1, 2, 3
db.execute("update table1 set column1=$a where column2 = $(b+c)")
```
You can read about using parameters in raw SQL Pony queries [here](https://docs.ponyorm.com/database.html#using-parameters-in-raw-sql-queries)

In order to escape $ sign you should write it as $$. But it is much better not to interpolate values inside a query and write it using $expressions:
```python
fields = dict_list[0].keys()
fields_str = ','.join(fields)
values = <...> # generate list of values
value_strings = ['($values[{}])'.format(i) for i, v in enumerate(values)]
updates = ['{table}.{field} = VALUES({table}.{field})'.format(table=table, field=f) for f in fields]
update_string = ', '.join(updates)
query = '''
        INSERT INTO {table} ({fields_str})
        VALUES {insert_values}
        ON DUPLICATE KEY UPDATE
        {update_string}
    '''.format(table=table, fields_str=fields_str, insert_values=', '.join(value_strings), update_string=update_string)
db.execute(query).fetchall()
```

**Comment by lukashambsch** [comment]
@kozlovsky Thanks for the quick response! I didn't see a way to do that upsert query with the dollar sign notation. I'll give it a try that way. I need it to take in a list of dictionaries that will use the keys as the fields and the values as the values for each dictionary. Is it possible to do this with the $ sign notation?

**Comment by kozlovsky** [comment]
If you write code specifically for MySQL, `escape_dict` should works too. In that case, just replace each `$` with `$$`. Also, I think, in your case it may be more efficient to use `escape_item`.

**Comment by lukashambsch** [comment]
I'll take a look at escape_item. Thanks again!
