### ISSUE TITLE
Database.execute duplicating percentage sign

### ISSUE THREAD

**Issue by lukashambsch** [ponyorm/pony#325]
I'm using a raw sql insert statement, but the percentage sign is being duplicated. I've tracked it down to this line in the code. 

https://github.com/ponyorm/pony/blob/08bce0b875befe3e3355894391629e7f43f261ac/pony/orm/core.py#L224

Is there a way to get around this? Possibly somewhere I should be setting the paramstyle?

**Comment by kozlovsky** [comment]
What database are you using? Can you show an example of query?

**Comment by lukashambsch** [comment]
I'm using mysql. Here is an example of a query:

```
INSERT INTO product (`sku`,`asin`,`title`,`user`,`marketplace`)
VALUES ('Marshalls_20180109_4_22.00/10.5%','B01FI911QO','',2,1),
	   ('4B-DAJQ-OM2O','B00JBF45W4','Capri Designs- Daily Journal - Hedgehog (Design by Sarah Watts) (Owl)',2,1),
	   ('4C-YWG4-HK9L','B00JBGIZLK','Capri Designs- Perpetual Wall Calendar - Hedgehog (Design by Sarah Watts)',2,1)
ON DUPLICATE KEY UPDATE product.`sku` = VALUES(product.`sku`),
					    product.`asin` = VALUES(product.`asin`),
					    product.`title` = VALUES(product.`title`),
					    product.`user` = VALUES(product.`user`),
					    product.`marketplace` = VALUES(product.`marketplace`);
```

**Comment by kozlovsky** [comment]
Thanks for reporting, I was able to reproduce the bug.

The problem happens when the query (1) contains % sign inside a literal value and (2) does not have any $parameter.

We will fix it in next release. But it is not a good practice to put values inside SQL query text, because it can lead to SQL injection. I recommend you to rewrite a query using query parameters:

```python
vals = [
    ('Marshalls_20180109_4_22.00/10.5%', 'B01FI911QO', '', 2, 1),
    ('4B-DAJQ-OM2O', 'B00JBF45W4', 'Capri Designs- Daily Journal - Hedgehog (Design by Sarah Watts) (Owl)', 2, 1),
    ('4C-YWG4-HK9L', 'B00JBGIZLK', 'Capri Designs- Perpetual Wall Calendar - Hedgehog (Design by Sarah Watts)', 2, 1)
]

sql = """
    INSERT INTO product (`sku`,`asin`,`title`,`user`,`marketplace`)
    VALUES
        ($vals[0][1], $vals[0][2], $vals[0][3], $vals[0][4], $vals[0][5]),
        ($vals[1][1], $vals[1][2], $vals[1][3], $vals[1][4], $vals[1][5]),
        ($vals[2][1], $vals[2][2], $vals[2][3], $vals[2][4], $vals[2][5]),
    ON DUPLICATE KEY UPDATE
        product.`sku` = VALUES(product.`sku`),
        product.`asin` = VALUES(product.`asin`),
        product.`title` = VALUES(product.`title`),
        product.`user` = VALUES(product.`user`),
        product.`marketplace` = VALUES(product.`marketplace`);
"""

db.execute(sql)
```

**Comment by kozlovsky** [comment]
If you really want to inject literals into string, until the bug is fixed you can get native connection to the database and use it to execute the query:

```python
connection = db.get_connection()
cursor = connection.cursor()
cursor.execute(sql)
```

**Comment by lukashambsch** [comment]
@kozlovsky I've been using this commit 29088380efa26bc6d9be38194189c46e1ada8a30, which fixes this bug. However, I'm seeing the same issue with dollar signs. When I install the 0.7.3 release, I don't see the issue with duplicated dollar signs, but I see this issue with the duplicated percentage signs.

 This is an issue that's corrupting our product data. Any ideas on how I can get both dollar signs and percentage signs escaping correctly?

**Comment by kozlovsky** [comment]
Thanks for reporting, it should be fixed now. I added some tests as well. The issue with dollars is slightly different then the issue with duplicated percentage signs: if you use `db.execute` or `db.select`, you need to replace each `$` in your SQL literals with `$$`, because `$foo` means a parameter. If the SQL text has no such parameters, you can just do
```python
sql = sql.replace('$', '$$')
db.execute(sql)
```
