### ISSUE TITLE
pony.orm.dbapiprovider.ProgrammingError: can't adapt type 'TrackedDict'

### ISSUE THREAD

**Issue by saggit** [ponyorm/pony#326]
I get an error after upgrade ponyorm version : 0.7.2 to 0.7.3,

site-packages/pony/orm/core.py(470)new_func()
    469                         if not do_retry: raise
--> 470                     finally: db_session.__exit__(exc_type, exc, tb)

the function is simple
@db_session
def save_sth():
    # do sth
    
I don't understand TrackedDict mean?

**Comment by sashaaero** [comment]
Hi! Can you make an example that we can run to reproduce the bug?
TrackedDict is an inner pony object, used for storing JSON values.

**Comment by kozlovsky** [comment]
This is the same bug as in #314, fixed in 6bb72b (release 0.7.4)
