### ISSUE TITLE
Enable Write Ahead logging for sqlite?

### ISSUE THREAD

**Issue by nadermx** [ponyorm/pony#329]
Hi, I was wondering how I would go about enabling write ahead logging for a sqlite db.

I know I have to send `PRAGMA journal_mode=WAL;` to sqlite, just not sure where in pony I would put it

**Comment by bjmgeek** [comment]
You can just use the `execute` method of the db object.
````
>>> from pony import orm
>>> db=orm.Database()
>>> db.bind(provider='sqlite',filename='/tmp/testdb.sqlite',create_db=True)
>>> db.execute('PRAGMA journal_mode=WAL')
````
