### ISSUE TITLE
 In  situation of  case sensitive , get method got MultipleObjectsFoundError

### ISSUE THREAD

**Issue by amorxj** [ponyorm/pony#343]
Object example：
```
class Resource(db.Entity):
    id = PrimaryKey(int, auto=True)
    xxx = Optional(str)
```
Step 1. Got `Resource(id=1,xxx="good")` and `Resource(id=2,xxx="Good")` stored 
Step 2   Use  `Resource.get(xxx="good")`  , I got `MultipleObjectsFoundError`

I just want to get  the “good” resource，not the “Good” one 。
Is there any parameter for `get` method to slove this problem ?
Or any other ways?

**Comment by amorxj** [comment]
I want case  sensitivity。

**Comment by kozlovsky** [comment]
Hi, do you use MySQL?

**Comment by amorxj** [comment]
yes，Mysql，@kozlovsky

**Comment by amorxj** [comment]
Ok, I got a solution。 
When creating database ，use  `utf8_bin`  or some other case-sensitive  collate as your  `DEFAULT COLLATE`  

I guess this problem is not  proper for Pony .  

Thanks for reply  @kozlovsky  @andreymal
