### ISSUE TITLE
Offset without limit

### ISSUE THREAD

**Issue by jonatanolofsson** [ponyorm/pony#344]
From what I can find in the code, offset cannot be added to a query without limiting the number of results: the limit argument to the limit() function is mandatory, and there is no other function to add only offset.

**Comment by sashaaero** [comment]
Hi! Can you please explain the case why do you need that?
In SQL `offset` is just a part of `limit` section. So you can't use `offset` without specifying `limit`.
Like:
```
SELECT *
FROM Table1
LIMIT 5 OFFSET 10
```

**Comment by jonatanolofsson** [comment]
You are correct that the offset (unfortunately and a known mis-design) is tied to the LIMIT command, leading to the following common work-around (see e.g. https://stackoverflow.com/questions/255517/mysql-offset-infinite-rows):
```
SELECT *
FROM Table1
LIMIT 18446744073709551610
OFFSET 10
```
where 18446744073709551610 is max for the BIGINT type.

As an example, I am working with a large sensor data dataset where I want to process all posts, except for the first N datapoints which are, as is common, discarded as they are sampled before the calibration has finished.

Granted, I can provide the large number to the .limit() function (or even monkey-patch the library myself), but a designated .offset() or even just a default value to the limit parameter in limit() would simplify the syntax.
