### ISSUE TITLE
Group by 

### ISSUE THREAD

**Issue by hubcin** [ponyorm/pony#348]
I have posted a question on stackoverflow for months but no one answered:
```
select substr(word,1,1) as alpha, count(*) as count
from words
group by substr(word,1,1);
```
How to implement this in pony ORM ??

**Comment by kozlovsky** [comment]
Hi, it should be easy:

```python
query = select(
    (person.name[0], count())
    for person in Person
)
```
(in your original query both table and column are called `words` and `word`, so I changed to `Person` and `name` for clarity)

The grouping happens automatically over all non-aggregated elements in expression part of generator

**Comment by hubcin** [comment]
@kozlovsky so, what is query after that? how do I get the name[0] and count from query object?
