### ISSUE TITLE
Relationships with create_tables=False

### ISSUE THREAD

**Issue by dmigo** [ponyorm/pony#351]
The intention is to have two simple classes representing two related tables that already exist in the db.  
The code is:

    from pony.orm import *
    db = Database()
    
    class System(db.Entity):
        _table_ = 'some', 'systems'
        
        system_id = PrimaryKey(int, auto=True)
        structures = Set('Structure')
    
    class Structure(db.Entity):
        _table_ = 'some', 'structures'
        structure_id = PrimaryKey(int, auto=True)
        system_id = Required(int)
        system = Required(System)
    
    db.bind(...)
    db.generate_mapping(create_tables=False)

I've tried to follow the approach I've seen [in the documentation](https://docs.ponyorm.com/working_with_relationships.html#working-with-entity-relationships), but executing the code above gives me:

> psycopg2.ProgrammingError: column structures.system does not exist  
> LINE 1: ...ctures"."structure_id", "structures"."system_id", "structure...  
>  
> HINT:  Perhaps you meant to reference the column "structures.system_id".

What is missing here?

PS I also created a [SO question](https://stackoverflow.com/questions/50587746/relationships-in-pony-orm-with-create-tables-false), since I wasn't sure which is preferred way of communications.

**Comment by kozlovsky** [comment]
Hi, I answered your question on StackOverflow:
https://stackoverflow.com/questions/50587746/relationships-in-pony-orm-with-create-tables-false/50607373#50607373

> PS I also created a SO question, since I wasn't sure which is preferred way of communications.

I think it is normal if you ask question on StackOverflow and then repost it here so we don't miss the question. You can also ask question in our telegram chat: https://telegram.me/ponyorm

**Comment by dmigo** [comment]
Thanks!
