### ISSUE TITLE
Moving items in collection

### ISSUE THREAD

**Issue by vegenera** [ponyorm/pony#359]
Hello!

Is it possible to move items in collection? Is it possible to change the "index"?

For example:

I have a playlist with music. It is necessary to move the song to position above or below another song(drag'n'drop at front).

**Playlist model:**

```python
class Playlist(db.Entity):
    playlist_id = PrimaryKey(str)
    title = Required(str, unique=True)
    sub_title = Required(str)
    songs = Set('Song')
```

**Song model:**

```python
class Song(db.Entity):
    track_id = PrimaryKey(str)
    title = Required(str)
    artist = Required(Artist)
    playlist = Set('Playlist')
```

I add music to playlist via "[add](https://docs.ponyorm.com/api_reference.html?highlight=add#Set.add)".
Is it possible to do this via "**many-to-many**" or only through as [json](https://docs.ponyorm.com/json.html?highlight=json)?

Thank you!

**Comment by sashaaero** [comment]
Hello.
I think that common way to do it is to create new entity 'SongInPlaylist' that contains song, playlist and order.
```
class SongInPlaylist(db.Entity):
    song = Required(Song)
    playlist = Required(Playlist)
    order = Required(int, unique=True)
    PrimaryKey(song, playlist)
```

And you change relation from `Song` and `Playlist`  to `SongInPlaylist`

**Comment by vegenera** [comment]
@sashaaero thank you!
