### ISSUE TITLE
0.7.5 Memory leak

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#370]
0.7.5 broke my website again :)

[![](https://i.imgur.com/FvbclWys.png)](https://i.imgur.com/FvbclWy.png)

```python
import gc
from pony.orm import * 

db = Database()

class Testing(db.Entity):
    description = Optional(LongStr)
    name = Required(str, 256)

db.bind('sqlite', ':memory:')
db.generate_mapping(create_tables=True)

# prepare data

print('fill database...')
with db_session:
    for i in range(20):
        Testing(description=str(i) * 4, name=str(i))

# test it!

@db_session
def testme():
    testing_list = list(Testing.select())


print('started')
i = 0
while True:
    i += 1
    if i % 100 == 0:
        gc.collect()  # actually it does nothing
    testme()
```

~5MB/s leaks on my laptop (faster without gc)

**Comment by andreymal** [comment]
Fun fact: the leak is gone when I ran my website with `FLASK_ENV=development` or `FLASK_DEBUG=1`. Dunno why

**Comment by sashaaero** [comment]
Hello! We are feeling sorry that you met such problems. We'll try to fix it as soon as possible.

**Comment by kozlovsky** [comment]
The memory leak should be fixed now. Can you check please?

**Comment by andreymal** [comment]
👍
[![](https://i.imgur.com/FUzOyjks.png)](https://i.imgur.com/FUzOyjk.png)
