### ISSUE TITLE
Coalesce of Json attributes should not check type

### ISSUE THREAD

**Issue by Vitalium** [ponyorm/pony#371]
If I try to coalesce Json attribute pony throws `TypeError: All arguments of coalesce() function should have the same type`, but in case with Json field we can not known what exactly type has an attribute. Maybe it should omit type check for Json attributes?

Here is example code:
```
select(coalesce(u.settings['remind_period'], 7) for u in User)
```

**Comment by sashaaero** [comment]
Hello, @Vitalium! Really we can't let it just go without type checking because it will lead to database error. To solve your problem we fixed type casting for JSON values, so you should explicitly cast it.
```python
select(coalesce(int(u.settings['remind_period']), 7) for u in User)
```

**Comment by Vitalium** [comment]
Thanks! Rational solution.
