### ISSUE TITLE
auto, non-int, Primary keys broken.

### ISSUE THREAD

**Issue by jdoig** [ponyorm/pony#374]
Upgrading from 0.7.2 to 0.7.5 caused breakage where non-ints are used as auto primary keys.
(In this case I have a table with a text pk that's generated by postgres)
https://github.com/ponyorm/pony/blob/orm/pony/orm/core.py?utf8=%E2%9C%93#L1911-L1912

**Comment by sashaaero** [comment]
Thanks for reporting. Fixed.
