### ISSUE TITLE
Pony Migrations `apply` not working for initial table creation

### ISSUE THREAD

**Issue by alxrsngrtn** [ponyorm/pony#378]
I'll reproduce the output of the workflow below for reproduction purposes. I have better information, however: I was able to pinpoint why the error was occurring and what to fix -- I just don't know where to make the change. 

In `migration.py::apply`, we read from the database and then partition the migrations into two lists: 

```
        with orm.db_session:
            applied = set(orm.select(m.name for m in migration_db.Migration))
            print(applied)

        applied_migrations = [m for m in migrations if m.name in applied]
        migrations_to_apply = [m for m in migrations if m.name not in applied]
```
I added a few print statements to see what was going on, namely this: 
`  print('applied vs unapplied: ', applied_migrations, migrations_to_apply)`
It revealed that the initial database schema creation was considered already applied: 
`applied vs unapplied:  [Migration('0001_initial')] []`

This, however, is my best guess as to what is going on. It's possible (better yet likely) that I have a configuration/setup issue and I'm just gung-ho about squashing bugs. 

## How to Reproduce
Here are the steps I took to reproduce the issue: 
1. Install the migrations branch of pony via #16 
Here is my exact version (i.e. from `pip list`): 
`pony                     0.8.dev0`

2. Create entities in a database. I packaged mine in a function called `init_db` that takes in a configuration dictionary. It does not call `bind`, `generate_mappings`, nor `connect`, it merely defines the entities.

Here is my (approximate) configuration dictionary (for testing): 
```
TEST = {
        'env': 'TEST',
        'debug': True,
        'migration_dir': 'migrations',
        'database': {
            'provider': 'sqlite',
            'filename': 'test.db',
            'create_db': True
        }
    }
```

3. Create a quick migration script. Here is mine: 
```
from <package>.config import TEST
from <package>.entities import init_db

init_db(TEST).migrate(migration_dir=TEST['migration_dir'], **TEST['database'])
```

4. Call `python migration.py make`. Output: 
```
GET NEW CONNECTION
RELEASE CONNECTION
Written: migrations/0001_initial.py
DISCONNECT
```
In my application an empty sqlite database is created. It has no tables besides the default. 

5. Call `python migration.py apply`. Output: 
```
GET NEW CONNECTION
RELEASE CONNECTION
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
PRAGMA foreign_keys = false
BEGIN IMMEDIATE TRANSACTION
SELECT "migration"."id", "migration"."name", "migration"."applied"
FROM "migration" "migration"
WHERE 0 = 1

COMMIT
PRAGMA foreign_keys = true
CLOSE CONNECTION
GET NEW CONNECTION
SWITCH TO AUTOCOMMIT MODE
SELECT DISTINCT "m"."name"
FROM "migration" "m"

RELEASE CONNECTION

All migrations are applied.
DISCONNECT
DISCONNECT
```

Notice that `All migrations are applied` is reached. This means that the database doesn't get initialized -- it considers that migration to already be applied.

6. Call `python migration.py list` to confirm: 
```
GET NEW CONNECTION
RELEASE CONNECTION
GET CONNECTION FROM THE LOCAL POOL
SWITCH TO AUTOCOMMIT MODE
SELECT "m"."id", "m"."name", "m"."applied"
FROM "migration" "m"
LIMIT 1

No Migration table. Please apply the initial migration.
RELEASE CONNECTION
DISCONNECT
```

**Comment by sashaaero** [comment]
Hello, @alxrsngrtn. Thanks for reporting. Seems that you have the same issue as one which was solved [here](https://github.com/ponyorm/pony/issues/384). If it doesn't please respond. Don't forget to update pony from github.
