### ISSUE TITLE
Foreign key constraint failed after Set.create

### ISSUE THREAD

**Issue by ranisalt** [ponyorm/pony#381]
I'm having the following error: `pony.orm.core.TransactionIntegrityError: Object Session[UUID('...')] cannot be stored in the database. IntegrityError: FOREIGN KEY constraint failed`

This happens on the following code:
```python
with orm.db_session:
    email = self.get_argument('email')

    user = orm.select(u for u in User if u.email == email).prefetch(User.password).first()
    if not user:
        raise HTTPError(status_code=403)

    password = self.get_argument('password')
    if not argon2.verify(password, user.password):
        raise HTTPError(status_code=403)

    session = user.sessions.create(remote_ip=self.request.remote_ip)
    self.set_secure_cookie('session', session.id.bytes)
```

The `set_secure_cookie` line never executes because of this crash. I can't understand why there can be a foreign key constraint error if the object is being created from the relationship set.

These are the problematic entities:
```python
class User(db.Entity):
    id = orm.PrimaryKey(uuid.UUID, default=uuid.uuid4)

    first_name = orm.Required(str, 35, lazy=True)
    last_name = orm.Required(str, 35, lazy=True)
    email = orm.Required(str, 254, unique=True, lazy=True)
    password = orm.Required(str, 80, lazy=True)

    sessions = orm.Set('Session')

class Session(db.Entity):
    id = orm.PrimaryKey(uuid.UUID, default=uuid.uuid4)

    user = orm.Required(User)
    remote_ip = orm.Required(str, 45)

    started_at = orm.Required(datetime, default=datetime.now)
```

**Comment by ranisalt** [comment]
It is a bug with SQLite, switching to PostgreSQL makes the error disappear.

**Comment by sashaaero** [comment]
Hello! You code contains some mistakes so we cannot reproduce this bug.
When you write `user = select(u for u in User if u.email == email).prefetch(User.password)` `user` object is not instance of `User` entity, it is `Query` object, so your code falls at `user.password` cause query object doesnt have attribute `password`.
I fixed this and my code works. If you can post some code that really gives that error we will take a look.

**Comment by ranisalt** [comment]
Sorry, fixed it. Accidentally cut out `.first()` when posting.

**Comment by sashaaero** [comment]
Yes, I fixed that by myself but still not able to reproduce.
