### ISSUE TITLE
Double left joins and coalesce casting

### ISSUE THREAD

**Issue by m35** [ponyorm/pony#383]
I have users, tracks, and ratings. Each user can rate each track differently. I want to list what rating every user gave to every song, but if a song isn't rated by a user, give it a default rating. In this example, there are no ratings, so the default value should be used for every song.

Here's the setup
```
from uuid import UUID, uuid4

from pony.orm import *

db = Database()

class User(db.Entity):
    id = PrimaryKey(UUID, default = uuid4)
    name = Required(str)
    ratings = Set(lambda: Rating)

class Track(db.Entity):
    id = PrimaryKey(UUID, default = uuid4)
    artist = Required(str)
    ratings = Set(lambda: Rating)

class Rating(db.Entity):
    user = Required(User)
    track = Required(Track)
    value = Required(int)
    PrimaryKey(user, track)

db.bind(provider='sqlite', filename=':memory:')

db.generate_mapping(create_tables=True)

set_sql_debug(True)

with db_session:

    u1 = User(name='John')
    u2 = User(name='Mary')
    u3 = User(name='Bob')
    t1 = Track(artist='Prius')
    t2 = Track(artist='Explorer')
    commit()

    left_join(coalesce(u.ratings.value, 99) for u in User for r in u.ratings).without_distinct()[:]
    left_join(coalesce(int(u.ratings.value), 99) for u in User for r in u.ratings).without_distinct()[:]
```
The first query throws an error "All arguments of coalesce() function should have the same type". I thought since `value` is an `int` I wouldn't need to cast it. Did I do something wrong?

The second query results in two left joins. I expected just one left join.
```
SELECT coalesce(CAST("rating"."value" AS integer), 1)
FROM "User" "u"
  LEFT JOIN "Rating" "r"
    ON "u"."id" = "r"."user"
  LEFT JOIN "Rating" "rating"
    ON "u"."id" = "rating"."user"

[1, 1, 1]
```
I think it should still return the results I want, but I've never tried doing two left joins. Am I doing something wrong here?

**Comment by Vitalium** [comment]
In both queries you use 2 `for` loops, but the second is unused.
You should do either like this:
`left_join(coalesce(int(u.ratings.value), 99) for u in User).without_distinct()[:]`
or:
`left_join(coalesce(int(r.value), 99) for u in User for r in u.ratings).without_distinct()[:]`

Both solutions generates almost the same SQL and gives the same result.

**Comment by sashaaero** [comment]
Hello. What Vitalium said was right. 
Double join of same table is something that you really want to achieve sometimes. So when you accessing two times `u.ratings` and `u.ratings.values` you might sometimes want to compare something. 
I close this issue for now but feel free to ask additional questions.
