### ISSUE TITLE
Unable to have circular references

### ISSUE THREAD

**Issue by martmists** [ponyorm/pony#388]
I'm currently moving from JSON to PostgresQL with Pony, but I've ruin into an issue.

Formerly, I used to have this:
```json
{
    "some_attr": "some_arg",
    "authors": ["id_1", "id_2"],
}
```

Pony did not allow lists, so I used object references instead:
```py
class Mod(db.Entity):
    id = PrimaryKey(str)
    title = Required(str)
    path = Required(str)
    released_at = Required(int)
    last_updated = Required(int)
    downloads = Required(int)
    authors = Set('User')
    verified = Required(bool)


class User(db.Entity):
    id = PrimaryKey(str)
    name = Required(str)
    bio = Required(str)
    mods = Set(Mod)
    favorites = Set(Mod)


class Review(db.Entity):
    id = PrimaryKey(str)
    mod = Required(str)
    message = Required(str)
    author = Required(str)
```

However, it says I need to use the `reverse` parameter instead. So, I set all Set() calls to have `reverse='id'` as kwarg, but it errors again. What am I supposed to do in a situation like this?

**Comment by andreymal** [comment]
```python
class Mod(db.Entity):
    ...
    authors = Set('User', reverse='mods')
    fav_authors = Set('User', reverse='favorites')


class User(db.Entity):
    ...
    mods = Set(Mod, reverse='authors')
    favorites = Set(Mod, reverse='fav_authors')

**Comment by martmists** [comment]
Oh, so it creates an entirely new table for both? That's kinda troublesome...

**Comment by andreymal** [comment]
Not sure what you mean, but many-to-many relationship will always create an additional table in any ORM

**Comment by martmists** [comment]
So I can't store lists of IDs somehow?

**Comment by andreymal** [comment]
You can store lists using [JSON Data Type](https://docs.ponyorm.com/json.html) (but this will not create a "true" many-to-many relationship of course)
