### ISSUE TITLE
TransactionError when trying to add relations

### ISSUE THREAD

**Issue by martmists** [ponyorm/pony#393]
Adding a Mod object defined as 
```python
class Mod(db.Entity, Base):
    id = PrimaryKey(str)
    ...
    authors = Set('User', reverse='mods')
```
with data
```python
{
 'id': 'unique_id_thingy', 
 ...,
 'authors': [User['some_id']]
}
```
raises `pony.orm.core.TransactionError: An attempt to mix objects belonging to different transactions`. According to some StackOverflow answers I should be able to use the ID, but then it raises a TypeError, expecting a User and getting a string.

**Comment by sashaaero** [comment]
Hello again, @martmists. 
You should take a look at [db_session at documentation](https://docs.ponyorm.com/api_reference.html?transactions-db-session#transactions-db-session).
This issue looks the same as your previous. Let's combine them and I'll give you answers there.

Also if you have questions about how Pony works it's better to ask us in our [Telegram group](https://t.me/ponyorm).
