### ISSUE TITLE
Troubles starting Google App Engine local development server

### ISSUE THREAD

**Issue by vtertre** [ponyorm/pony#404]
Hi,

I'm having troubles starting an app with PonyORM on a local Google App Engine server (using dev_appserver.py).
My gcloud SDK is up to date (224.0.0).

![image](https://user-images.githubusercontent.com/3511094/48358262-aefd7b80-e69a-11e8-987c-1ac25fb14d20.png)

If I skip importing dev_appserver in pony/\_\_init\_\_.py, it seems to be working fine.

Any idea how I can fix it?

Thanks

**Comment by sashaaero** [comment]
Thanks for reporting. Should work now.
