### ISSUE TITLE
[Critical] [PonyORM Editor] Spontaneously loses changes (forces refresh without ability to save)

### ISSUE THREAD

**Issue by Elijas** [ponyorm/pony#412]
To reproduce:
1. Add new relationship
2. Start selecting the second entity
3. Remember that you haven't created it yet
4. Click on empty space expecting modal to close
5. Whole page becomes white, leaving you with no other option than to refresh and lose all changes

Lost quite some work until got into the habit of saving after every change

GIF:
![gif 1](https://user-images.githubusercontent.com/4084885/51259747-738e6e80-19b5-11e9-9b9b-f81459bfc9f0.gif)

**Comment by makarov-roman** [comment]
Thank you for detailed report. It helps a lot. I going to deploy fix asap

**Comment by Elijas** [comment]
@makarov-roman Thanks for a swift response! Thrilled to hear that! :blush:

**Comment by amalashkevich** [comment]
Thanks for reporting!
