### ISSUE TITLE
pony (0.7.6) decimal.Decimal converter retains only 2 significant digits

### ISSUE THREAD

**Issue by jvickroy** [ponyorm/pony#413]
I've hacked class SQLiteDecimalConverter in ...\Lib\site-packages\pony\orm\dbproviders\sqlite.py to support
Decimal ('infinity') and Decimal values < 0.01.  I would like the next release of Pony to handle these use cases.  My hack follows:
```
class SQLiteDecimalConverter(dbapiprovider.DecimalConverter):
    def sql2py(converter, val):
        try: val = Decimal(str(val))
        except: return val
##<jv>        exp = converter.exp ... this truncates to 2 significant digits which is inappropriate for camera exposures
##<jv>        if exp is not None: val = val.quantize(exp)
        exp = Decimal('1.000000')                                       ##<jv> to support short camera exposures
        if exp is not None and val.is_finite(): val = val.quantize(exp) ##<jv> to handle val=Decimal('infinity')
        return val
    def py2sql(converter, val):
        if type(val) is not Decimal: val = Decimal(val)
##<jv>        exp = converter.exp ... this truncates to 2 significant digits which is inappropriate for camera exposures
##<jv>        if exp is not None: val = val.quantize(exp)
        exp = Decimal('1.000000')                                       ##<jv> to support short camera exposures
        if exp is not None and val.is_finite(): val = val.quantize(exp) ##<jv> to handle val=Decimal('infinity')
        return str(val)

```

**Comment by kozlovsky** [comment]
Hi!

By default, Pony uses Decimal with scale 12 and precision 2, that is, it keeps 2 digits after floating point
https://docs.ponyorm.org/api_reference.html?highlight=precision#decimal-scale-and-precision

You can explicitly set another precision

Regarding infinity, SQL standard does not support it (read this StackOverflow [answer](https://stackoverflow.com/a/41953005/1706814)). So, PostgreSQL, MySQL and Oracle databases don't support infinity decimal values.

In principle, we can add support of infinity values in SQLite only, as we store values as strings, but it may be problematic. For example, when someone does SELECT with ORDER BY, the resulting order will be not correct. This is the reason we don't want to add this.

You can use `NULL` values (`None` in Python) to represent infinity values. To do this, declare you Decimal column as Optional to allow NULL values in it.

**Comment by jvickroy** [comment]
Understood.  Thanks for your informative reply.
