### ISSUE TITLE
TypeError: Expression has unsupported type 'Required'

### ISSUE THREAD

**Issue by Spenhouet** [ponyorm/pony#424]
While running the code bellow I'm getting the following error:

> TypeError: Expression `Task.duration` has unsupported type 'Required'

I don't get where this error is coming from and what I can do to resolve it.
Changing to `Optional` just yielded:

> TypeError: Expression `Task.duration` has unsupported type 'Optional'

What can I do? Is this a bug?

Minimal code that fails:

```
from pony.orm import Database, PrimaryKey, Required, Optional, set_sql_debug, count
from datetime import date

db = Database()

class Task(db.Entity):
    _table_ = "PRTASK"
    id = PrimaryKey(int, column="PRID", auto=True)
    duration = Required(float, column="PRDURATION")

db.bind(provider='oracle', user='***', password='***', dsn='***')
db.generate_mapping(create_tables=False)
set_sql_debug(True)

with db_session:
    q_results = (Task.duration for s in Task)
    num_results = count(q_results)  # <- Error happens here
```

_pony version: 0.7.9_

**Comment by Spenhouet** [comment]
It seems I misunderstood the needed syntax.

I needed to do the selection like this:

`getattr(s, Task.duration.name)`

In the example above:

```
with db_session:
    q_results = (getattr(s, Task.duration.name) for s in Task)
    num_results = count(q_results)
```

**Comment by andreymal** [comment]
Maybe just `s.duration`?

**Comment by Spenhouet** [comment]
> Maybe just `s.duration`?

The attribute is dynamic and is within a variable, therefore the `getattr()` solution.
