### ISSUE TITLE
Can't handle my account - serious issue.

### ISSUE THREAD

**Issue by MicheleBerra** [ponyorm/pony#436]
I can't remove my paid subscription (user chartside) nor delete my account. 

My card is about to expire and this is a very big issue for me.

**Comment by andreymal** [comment]
How is this related to Pony ORM?

**Comment by MicheleBerra** [comment]
I wrote a bit less then I should have. It is a paid subscription to ponyORM online diagram.

**Comment by amalashkevich** [comment]
Hi Michele,

I tried to reply to your request, but got an error I copied below. No worries, I’ll assist you on this.

Alexey

The error I got when tried to send an email:

The mail system

<mikiberra@gmail.com>: host gmail-smtp-in.l.google.com[64.233.184.27] said:
   550-5.1.1 The email account that you tried to reach does not exist. Please
   try 550-5.1.1 double-checking the recipient's email address for typos or
   550-5.1.1 unnecessary spaces. Learn more at 550 5.1.1

**Comment by MicheleBerra** [comment]
It’s mikyberra@gmail.com
