### ISSUE TITLE
pony.orm.core.ERDiagramError: Mapping is not generated for entity 'Person'

### ISSUE THREAD

**Issue by ghost** [ponyorm/pony#44]
I tried to follow instructions: http://doc.ponyorm.com/firststeps.html

```
from pony.orm import *

db = Database("mysql", host="192.168.1.117", user="usr", passwd="pwd", db="test")

class Person(db.Entity):
    name = Required(unicode)
    age = Required(int)
    cars = Set("Car")

class Car(db.Entity):
    make = Required(unicode)
    model = Required(unicode)
    owner = Required(Person)

sql_debug(True)
#db.generate_mapping(create_tables=True) # --->>>> I commented this after tables creation otherwise I received pony.orm.core.TransactionError: db_session is required when working with the database

p1 = Person(name='John', age=20)
p2 = Person(name='Mary', age=22)
p3 = Person(name='Bob', age=30)
c1 = Car(make='Toyota', model='Prius', owner=p2)
c2 = Car(make='Ford', model='Explorer', owner=p3)
commit()
```

exception:
pony.orm.core.ERDiagramError: Mapping is not generated for entity 'Person'

What am I doing wrong? :\
Desired tables were generated inside database, but that's all what I can get.

**Comment by richardjlyon** [comment]
In "Getting started with Pony", you instruct us to invoke `db.bind()`. In this comment you note that your documentation fails to distinguish adequately between running the example in interactive mode, and in code. You provide an example of code. The code doesn't reference `db.bind()`.

I can't make your code work from the documentation you provide.
