### ISSUE TITLE
Unique attributes are lazy loaded

### ISSUE THREAD

**Issue by gabriel-ilie** [ponyorm/pony#451]
python2.7
pony orm 0.7.10

------------------------------------------------
from pony.orm import *
db = Database()

class A(db.Entity):
    name=Required(str, unique=True)
    b = Set('B')

class B(db.Entity):
    x = Required(str)
    a = Required('A')

db.bind('sqlite', ':memory:')
db.generate_mapping(create_tables=True)

with db_session:
    a = A(name='name')
    b = B(a=a, x='x')

with db_session:
    b = B.get(x='x')
    #b.a.load()
    b.a.name = 'sss'
    
====================>
Traceback (most recent call last):
  File "/mnt/hgfs/share/pony_orm_unique_keys_not_loaded.py", line 22, in <module>
    b.a.name = 'sss'
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 2357, in __set__
    for undo_func in reversed(undo_funcs): undo_func()
  File "/usr/local/lib/python2.7/dist-packages/pony/orm/core.py", line 2323, in undo_func
    if old_val is NOT_LOADED: obj._vals_.pop(attr)
KeyError: A.name

If I uncomment << b.a.load() >> everything works as expected; 
If I use << b.a.set(name='sss') >> everything works as expected.
If I make name attribute not unique everything works as expected.
If I specify lazy=False for name it is still lazy loaded.

**Comment by ChiliConSql** [comment]
I am having the same issue.
python 3.7
pony 0.7.10

any suggestions?
