### ISSUE TITLE
docs.ponyorm.org https certificate expired 3 days ago

### ISSUE THREAD

**Issue by kregester** [ponyorm/pony#458]
![Screen Shot 2019-08-12 at 1 46 53 PM](https://user-images.githubusercontent.com/34080296/62897383-fedfa080-bd07-11e9-9233-227931100c30.png)

**Comment by tuffnatty** [comment]
@kregester seems to be ok at the moment

**Comment by sashaaero** [comment]
Yeah. Thanks for reporting. This issue is already solved.
