### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by societymartingale** [ponyorm/pony#472]
Setup.py restricts Pony to Python 3.7 and below. Can 3.8 be added?

**Comment by flypenguin** [comment]
I would consider this critical. most package managers for non-linux (homebrew, chocolatey) have switched to python 3.8 now or will soon. installing anything with a pony dependency will fail then.

**Comment by sashaaero** [comment]
Since Python 3.8 adds some new syntax we should take a careful look on the new bytecode and fix if something changed.
It is not just updating setup file, but we'll implement this asap.

**Comment by kozlovsky** [comment]
Thanks for reminding, all tests passed now in Python 3.8.
I added Python 3.8 support in setup.py
Official release will be at Monday

**Comment by jdevera** [comment]
Is there an updated plan for that release?

**Comment by kozlovsky** [comment]
Sorry for delay, will release in a few hours
