### ISSUE TITLE
Please add support for Python 3.9

### ISSUE THREAD

**Issue by mgorny** [ponyorm/pony#530]
Python 3.9 is really close to the final release, and apparently supporting it requires a lot of work in Pony (e.g. because Python changed its AST a lot). Could you please consider starting to work on that?

**Comment by sashaaero** [comment]
Hello! In Pony we care about bytecode changes. We use deprecated AST which is build by ourselves, so AST changes wont affect.

**Comment by kozlovsky** [comment]
Fixed in dea19b2
