### ISSUE TITLE
Question: Can Python id() builtin lead to hard to debug bug?

### ISSUE THREAD

**Issue by Ryuno-Ki** [ponyorm/pony#541]
While working on #537 I walked through the codebase and discovered the use of

https://github.com/ponyorm/pony/blob/52720af1728ab2931364be8615e18ad8714a7c9e/pony/utils/utils.py#L118

which was introduced in https://github.com/ponyorm/pony/commit/6495daad813805e08ee73db065b693755713d5ae as a response to #276 and released as v0.7.13.

[From the docs](https://docs.python.org/3/library/functions.html#id), it says:

> Return the “identity” of an object. This is an integer which is guaranteed to be unique and constant for this object during its lifetime. Two objects with non-overlapping lifetimes may have the same id() value.
> 
> **CPython implementation detail**: This is the address of the object in memory.

I wonder, what happens if the object gets destroyed and later another object receives this memory address?

From what I can see, `codeobjects` dictionary never gets cleared.

Sure, the chances are pretty low, but if this happens, you've a hard-to-reproduce error.
Can you use an UUID or something instead?

**Comment by kozlovsky** [comment]
> I wonder, what happens if the object gets destroyed

`codeobjects` dict holds references to all used codeobject instances, so they cannot be garbage collected
