### ISSUE TITLE
Flask integration fails with PRESERVE_CONTEXT_ON_EXCEPTION=True (AssertionError)

### ISSUE THREAD

**Issue by andreymal** [ponyorm/pony#575]
I got tired of attaching `@db_session` to every view function and decided to try the official Flask integration (`pony.flask.Pony(flask_app)`).

To investigate the behavior, I simulated an error inside a view function:

```python
@app.route('/error-test/')
def error_test():
    raise RuntimeError('test')
```

I stared flask server with `FLASK_ENV=development`.

When I opened this page first time, I got "friendly Werkzeug powered traceback interpreter" with RuntimeError as expected.

But when I refreshed this page few time, I got AssertionError instead, and after that the server completely stopped working until restart:

```
127.0.0.1 - - [27/Nov/2020 16:27:04] "GET /error-test/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  [...]
  File "lib/python3.6/site-packages/flask/app.py", line 2242, in preprocess_request
    rv = func()
  File "lib/python3.6/site-packages/pony/flask/__init__.py", line 8, in _enter_session
    session.__enter__()
  File "lib/python3.6/site-packages/pony/orm/core.py", line 464, in __enter__
    db_session._enter()
  File "lib/python3.6/site-packages/pony/orm/core.py", line 467, in _enter
    assert not local.db_context_counter
AssertionError
```

After a little research, I figured out that `teardown_request` is not called - perhaps this is the cause of the problem. When I start the server with `FLASK_ENV=production` everything works fine.

However, it would be nice if the Pony ORM became compatible with `FLASK_ENV=development` and didn't break itself due to the Werkzeug debugger.

![](https://i.imgur.com/NBRMpRa.png)

**Comment by andreymal** [comment]
It seems it's a duplicate of #481. `PRESERVE_CONTEXT_ON_EXCEPTION=False` can help, but I want to preserve it :)

**Comment by zgoda** [comment]
Indeed, this may be useful if you use web debugger. Not my case though as I'm writing headless apps mostly so discarding context is valid workaround.

**Comment by andreymal** [comment]
[Something changed in Flask 2.2](https://github.com/pallets/flask/pull/4666), `PRESERVE_CONTEXT_ON_EXCEPTION` has been removed and everything seems to work fine now
