### ISSUE TITLE
[Question], how can i push a trigger/function with pony ? 

### ISSUE THREAD

**Issue by OlivierArgentieri** [ponyorm/pony#587]
To begin, sorry if this information is in the documentation, but i can't find it.

I need to init my database with some data, so i have a "seed" layers, and in this layer, i want to create a function/trigger on a table.

So, i have made this raw sql query (postgres) :
```sql
CREATE OR REPLACE FUNCTION OnInsTask() RETURNS TRIGGER AS $$
    DECLARE
         v_shot INTEGER;
         v_asset INTEGER;
    BEGIN
        IF (v_shot = NULL AND v_asset = NULL ) THEN
            RAISE 'Shot or Asset is REQUIRED';
        END IF;
    END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER TrigInsTask
BEFORE INSERT OR UPDATE ON public.task
FOR EACH ROW execute procedure OnInsTask()
```

(don't judge it's just for testing/wip)

And my question is just, how can i past this string to raw_sql() function directly.

Because, in the documentation i found only examples and explanation with select, where etc on table.

Thank you

**Comment by jgirardet** [comment]
Look at https://docs.ponyorm.org/api_reference.html#entity-hooks and https://docs.ponyorm.org/api_reference.html#Database.execute

**Comment by OlivierArgentieri** [comment]
This is exactly what i was looking for, i will try this,
Thank you !
