### ISSUE TITLE
Deprecation Warning for thirdparty/compiler/ in Python 3.9

### ISSUE THREAD

**Issue by cmacht** [ponyorm/pony#598]
Using pytest in Python 3.9.4 outputs two deprecation warnings:

`DeprecationWarning: The parser module is deprecated and will be removed in future versions of Python`
[thirdparty/compiler/transformer.py:32](https://github.com/ponyorm/pony/blob/0c221d21e99752b8520b6a876c94b055e92f6a9d/pony/thirdparty/compiler/transformer.py#L32)
`DeprecationWarning: The symbol module is deprecated and will be removed in future versions of Python`
[thirdparty/compiler/transformer.py:33](https://github.com/ponyorm/pony/blob/0c221d21e99752b8520b6a876c94b055e92f6a9d/pony/thirdparty/compiler/transformer.py#L33) 

This was announced in the [Python 3.9 release](https://docs.python.org/3/whatsnew/3.9.html#new-parser), stating that the old [parser module](https://docs.python.org/3/library/parser.html) will be deleted and that [ast module](https://docs.python.org/3/library/ast.html#module-ast) should be used instead.

**Comment by gimpel-cs** [comment]
**Will there be a Pony ORM for Python 3.10 and beyond?**

As Alexandar shows in https://stackoverflow.com/questions/16115713/how-pony-orm-does-its-tricks Pony heavily depends on the Python parser.  As far as I understand the new ast module has the same functionality as the old parser und produces the same (or similar) AST, but I found no information if the new parser may be used as a drop-in replacement. And the symbol module will be also removed.

(I'm just writing a small web application and Pony is the first choice as ORM.)

**Comment by tonycpsu** [comment]
@kozlovsky: Any chance you could give us a sense of how much work is involved in adding Python 3.10 support given the removal of `parser` and `symbol`?

**Comment by spl0k** [comment]
@kozlovsky we are now next month. Any update from the Python 3.10 front?

**Comment by sashaaero** [comment]
Hello @spl0k 
Work is half way done. You can see it here https://github.com/ponyorm/pony/commits/py_3_10_dev

**Comment by baldurmen** [comment]
Looking at this branch, it seems all the tests pass on Python 3.10. Anything blocking a new release?

**Comment by cmacht** [comment]
> Looking at this branch, it seems all the tests pass on Python 3.10. Anything blocking a new release?

When I mentioned your question, @kozlovsky told me that the 3.10 tests are fine, but that they still need to make sure compatability with previous versions is not affected.

**Comment by cmacht** [comment]
PonyORM 0.7.15 release candidate 1 with support for Python 3.10 and the `ast` module was just released:
https://github.com/ponyorm/pony/releases/tag/v0.7.15rc1
