### ISSUE TITLE
how to generate geometry attribute?

### ISSUE THREAD

**Issue by VagnerBelfort** [ponyorm/pony#611]
I have a database that has a geometry type field. how do I generate this attribute?

table postgres:

![image](https://user-images.githubusercontent.com/46332453/133833174-8fd73956-aa2c-49a3-aac5-544f49d17ff0.png)

```
class Segmentos_ruas_log(db.Entity):
    id_segmentos_ruas = PrimaryKey(int, auto=True)
    nome = Required(str)
    nome_rua = Required(str)
    geom = Required(**??????**)
```

**Comment by sashaaero** [comment]
Hello!
Maybe this can help? https://docs.ponyorm.org/api_reference.html?highlight=sql_type#cmdoption-arg-sql_type

**Comment by VagnerBelfort** [comment]
I understand that I need to put the data type... when I read this table in pandas the data is as MULTILINESTRING, I would like to know how to define this data type in pony.
