### ISSUE TITLE
Error too many connections to postgres database

### ISSUE THREAD

**Issue by VagnerBelfort** [ponyorm/pony#615]
Hello!
I'm using pony for a flask application.
But when with a time the maximum connection with postgres breaks.
I get the following error:
pony.orm.dbapiprovider.OperationalError: FATAL: sorry, too many clients already

The pony is generating several connections and does not terminate it with each request?
Could someone help me with this?

**Comment by yxlwfds** [comment]
pony no pool num config?

**Comment by VagnerBelfort** [comment]
Hi guys!

the problem I was having was because I had pony and sqlalchemy installed in the same env, with that I was generating conflict and creating several connections in postgres.

I fixed the error by removing sqlalchemy from env
