### ISSUE TITLE
Extension for Flask

### ISSUE THREAD

**Issue by kasperhj** [ponyorm/pony#62]
Having a 'native' extension for Flask would be very nice, especially for larger project where the application factory pattern is essential.

**Comment by fabirovsky** [comment]
Hi, @kasperhj . 
I just found this https://github.com/kyzima-spb/flask-pony .
May you will like it.

**Comment by kozlovsky** [comment]
Hi, @kasperhj!
It might be a bit late but we've released it.
https://docs.ponyorm.com/integration_with_flask.html

**Comment by kozlovsky** [comment]
Hi, @kasperhj!
Now Pony included `pony.flask` subpackage which provides basic integration with Flask.
https://docs.ponyorm.com/integration_with_flask.html

We make it subpackage so it does not require installing additional libraries. Also, both `flask_pony` and `flask_ponyorm` names were already taken on PyPI.

[`flask-pony`](https://github.com/kyzima-spb/flask-pony) is a more traditionally looked Flask extension made by another developer which provides some additional features like generic views for CRUD form.
