### ISSUE TITLE
Add ability to specify sorting criteria on list of related entities

### ISSUE THREAD

**Issue by socketpair** [ponyorm/pony#65]
Something like this:

```
print ForwardZone[42].interfaces.order_by(desc(Interface.number))
```

```
SELECT "T1"."interface"
FROM "ForwardZone_Interface" "T1"
WHERE "T1"."forwardzone" = ?
---> missing:  order by  "T1".interface desc <-----
[42]
```

Помню, я недавно спрашивал про сортировку, и реально случайно попал на такую же ситуацию :) на этот раз мне нужно выдавать в веб-интерфейс именно сортированные элементы...Либо, мне нужен пример как реализовать вышеприведённый SQL-пример. M2M таблица-то недоступна без хаков!

**Comment by kozlovsky** [comment]
We just added the following methods to collections as part of Pony ORM 0.6.1 release:

```python
s = Student[1]
s.courses.select(lambda c: c.semester >= 2)
s.courses.filter(lambda c: c.semester >= 2)  # the synonym to the select
s.courses.order_by(Course.name)
s.courses.page(1, pagesize=10)
s.courses.limit(5, offset=10)
s.courses.random(3)
```

Currently the syntax suggested by Jason (that is, `select(course for course in s.courses)`) is not supported, but I think we should add it in PonyORM 0.6.2
