### ISSUE TITLE
python3.12 support

### ISSUE THREAD

**Issue by py-radicz** [ponyorm/pony#694]
Is it possible to add support for python3.12? 

It seems quite compatible for doing queries like `db.Entity.select()`.. but when I do `db.Entity.select(lambda x: x.attr == y)` I'll get  `IndexError: tuple index out of range` raising from decompiler on line 209 e.g 

```
    arg = [code.co_names[oparg]]
           ~~~~~~~~~~~~~^^^^^^^
```

**Comment by kozlovsky** [comment]
Fixed in #713 by @black-sliver
